### ISSUE TITLE
OpenSSL::PKey::EC.newのExceptionの説明で、名前空間の階層が間違っている

### ISSUE THREAD

**Issue by hirura** [rurema/doctree#1250]
`OpenSSL::PKey::EC.new`のExceptionの説明が、`OpenSSL::PKey::EC::ECError`になっています。

正しくは、`OpenSSL::PKey::ECError`のはずです。

**Comment by sho-h** [comment]
#1252 のマージ後に `$ grep OpenSSL::PKey::EC::ECError refm/**/*` で他にない事を確認しました。
