### ISSUE TITLE
クラス定義文

### ISSUE THREAD

**Issue by VSlqm9YmnI7cPjSk** [rurema/doctree#129]
http://docs.ruby-lang.org/ja/2.1.0/doc/spec=2feval.html

> クラス定義文の評価値を得ることはできません。

次の記事の「モジュール定義文」と同じく、「最後に評価した本体の式の値」ではないですか？

書式についても、次の記事の「モジュール定義文」の方は「本体」と書かれていますが、
クラス定義文の方は「式」と書かれているのも気になります。

> 一方、もし同名のクラスがすでにある場合はそれを使います。
> そのときスーパー クラス式が指定されており、その結果と得たクラスのスーパークラスが
> (equal? において) 違うときは新しいクラスを生成します。 

これはどういう意味でしょうか？

class C1; end
class C2; end
class S < C1; end
class S < C2; end

こういうコードのことを言っているのでしょうか？

**Comment by okkez** [comment]
古い内容になっていたので修正しました。
ありがとうございます。
