### ISSUE TITLE
while／untilが返す値

### ISSUE THREAD

**Issue by VSlqm9YmnI7cPjSk** [rurema/doctree#133]
http://docs.ruby-lang.org/ja/2.1.0/doc/spec=2fprogram.html

> 値を返さない式の例
> while, until, while 修飾式, until 修飾式

http://docs.ruby-lang.org/ja/2.1.0/doc/spec=2fcontrol.html

> while は nil を返します。
> while 修飾した式は nil を返します。
> until は nil を返します。
> until 修飾した式は nil を返します。

「値を返さない」と「nilを返す」は大違いではないですか？
なぜなら、 http://docs.ruby-lang.org/ja/2.1.0/doc/spec=2fcontrol.html には、

> 値を返さない式を代入式の右辺に置くと parse error になります

と書いてあるからです。

**Comment by okkez** [comment]
> while は nil を返します。
> while 修飾した式は nil を返します。
> until は nil を返します。
> until 修飾した式は nil を返します。

は正しいです。while修飾した式とは以下のようなものです。

```ruby
x = (a = :a while false)
p x # => nil
```

一方以下は syntax error になります。

```ruby
a = while fase
# syntax error, unexpected end-of-input, expecting keyword_end
```
