### ISSUE TITLE
サンプルコード中の __END__ 以降が表示されない

### ISSUE THREAD

**Issue by tbpgr** [rurema/doctree#1366]
`__END__` をサンプルコード内で使うと以降が切れます

* https://github.com/rurema/doctree/pull/1340 等

![_081118_042141_am](https://user-images.githubusercontent.com/4787509/43977112-0d1bbdb0-9d1e-11e8-94f0-e7ea8dcdd3e4.jpg)

実際には `__END__` 以降に

```
header1,header2
row1_1,row1_2
row2_1,row2_2
```

がある。

**Comment by sho-h** [comment]
あらら...とりあえず修正までの間は該当のファイルは旧形式のサンプルにしました。修正後にrevertしようと思います。

https://docs.ruby-lang.org/ja/2.5.0/method/CSV/i/gets.html などのソースを見ても特に「HTMLは何かしら出力されてるけど隠れてる」といった事はなさそうです。

/path/to/db/method/-c-s-v/i.gets.csv など見ると以下のようになってますので、SyntaxHighlighterの問題のようです。

```
//emlist[例][ruby]{
require "csv"

csv = CSV.new(DATA.read)
csv.readline # => ["header1", "header2"]
csv.readline # => ["row1_1", "row1_2"]

__END__
header1,header2
row1_1,row1_2
//}
```

lib/bitclust/syntax_highlighter.rbを見るにon_defaultで__END__自体は処理されてそうな感じですが、それ以降でイベントが上がってないのではないかと。Ripper::SCANNER_EVENTSにイベントもなさそうですし、Ripper::Filterの@__lexerをinspectした範囲でも持ってなさそうですので、かっこ悪いですけど以下などon___end__を定義して頑張るしか現状なさそうと思いました。

```
def on___end__(token, data)
  style = COLORS[:__end__]
  d = 元ソース.lines[self.lineno..-1]
  data << "<span class=\"#{style}\">#{d}</span>"
end
```

**Comment by sho-h** [comment]
↑__END__そのものを入れ忘れてるので最低でもそれを追記する必要ありです。

**Comment by tbpgr** [comment]
>あらら...とりあえず修正までの間は該当のファイルは旧形式のサンプルにしました。修正後にrevertしようと思います。

ありがとうございます 🙏

**Comment by okkez** [comment]
BitClust 1.2.1 をリリースしました。docs.ruby-lang.org の BitClust も更新しておきました。

**Comment by sho-h** [comment]
revertしてた分も元に戻しましたー。
