### ISSUE TITLE
CIでmisspellを走らせたい

### ISSUE THREAD

**Issue by pocke** [rurema/doctree#1376]
https://github.com/rurema/doctree/pull/1223#discussion_r210209160
このPRでレビューをもらって、タイポを自動で検出できるmisspellというツールを導入すると良いのではと思いました。

https://github.com/client9/misspell

misspellはブラックリスト方式(予め列挙されたタイポっぽい単語にマッチしたものにのみ警告を出す)ので、誤検知はかなり少ないです。なので導入はしやすいと思います。

ためしにdoctreeのコードにたいして実行してみたところ、いくつかのタイポが検出されました。

```bash
$ misspell $(git ls-files)
refm/api/src/drb/DRbUnknown:73:4: "unknwon" is a misspelling of "unknown"
refm/api/src/rexml/doctype.rd:337:28: "Decleration" is a misspelling of "Declaration"
refm/capi/src/process.c.rd:6:20: "addopt" is a misspelling of "adopt"
refm/api/src/xmlrpc/BasicServer:25:30: "paramter" is a misspelling of "parameter"
refm/doc/news/1.8.4.rd:569:54: "modifires" is a misspelling of "modifiers"
refm/doc/news/1.8.4.rd:988:11: "extention" is a misspelling of "extension"
refm/doc/news/2_2_0.rd:248:18: "addopt" is a misspelling of "adopt"
```

見た感じ`addopt`は誤検知かな？と思いましたが、他のものは誤検知ではないと思います(ちゃんと見てないので間違ってたらすみません)

やりたいこと
==

今回見つかったタイポが誤検知じゃないことを確認し修正することと、CIでmisspellを走らせることをしたいと思っています。

CIでは、misspellをgo getした上で、上記コマンドを実行すれば良さそうです。
誤検知する単語は`misspell -i addopt`のようにignoreオプションが使えるので、それで対応できそうです。

誰がやるか
===

とくに異論がでなければ、私の手があいたときにやろうかなと思っていますが、さっと導入したい人がいたらやっていただいても全然問題ないです

**Comment by sho-h** [comment]
おー、これはうれしいですね。

> 見た感じaddoptは誤検知かな？と思いましたが、他のものは誤検知ではないと思います(ちゃんと見てないので間違ってたらすみません)

addoptは確かに誤検知のようです。2.1までprocess.cにあった関数ですね。他は合ってる気がします。

> とくに異論がでなければ、私の手があいたときにやろうかなと思っていますが、さっと導入したい人がいたらやっていただいても全然問題ないです

異論ないので +1 です。

現状それっぽいものといえば、`@param` などをtypoすると以下に引っかかって怒られるくらいなのでそれが集約できると嬉しいくらいでした。(Rakefileの方から該当の行を削除して、辞書に追加できるとうれしい)

* https://github.com/rurema/doctree/blob/master/Rakefile#L101-L108

ただ、集約については辞書の追加方法を教えていただければmisspellの導入後に僕の方で対応ということでも問題ないかと思います。
