### ISSUE TITLE
フィードバックしやすくする

### ISSUE THREAD

**Issue by znz** [rurema/doctree#1421]
「このマニュアルのヘルプ」のページに「お問い合わせ」として github へのリンクがありますが、全ページの footer にリンクがあると良さそうです。

また、[GitHub の Issue Template を複数設定して使い分ける](https://qiita.com/suzuki-hoge/items/04de7d779bed6572bb99) のように issue template を複数用意して、「どのページへの指摘なのか」をテンプレートに入れて、記入してもらいやすくすると良さそうに思いました。

**Comment by hanachin** [comment]
bitclustの方にもにたissueがあり
フィードバックリンクの改善 https://github.com/rurema/bitclust/issues/92

以下でリンクは追加されているからcloseしてもよさそう?
Add feedback link to footer https://github.com/rurema/bitclust/pull/63

**Comment by znz** [comment]
edit リンクでかなり改善されているので close します。
