### ISSUE TITLE
File.utime の引数の順番がバラバラ

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#1431]
以下の `@param` の順番をatime, mtime, filenameの順にしたい。また、filenameは複数指定できるような記載にしたい。

* https://docs.ruby-lang.org/ja/2.5.0/method/File/s/utime.html

**Comment by sho-h** [comment]
.lutimeも。もしかしたら昔は順番が違って1個しか指定できなかったのかもしれないので一応確認してからにする。

* https://docs.ruby-lang.org/ja/2.5.0/method/File/s/lutime.html

**Comment by nico-hn** [comment]
#1425はご対応下さりありがとうございました。

引数の順番について、さしあたり調べてみた結果を報告させていただきます。

https://gist.github.com/nico-hn/369577c4b23b00aad4f5fc12cef84013#file-test_file_utime-rb
のようなスクリプトで試してみたところ、

filenameの複数指定も含め1.8.7から2.6.0-preview2まで全てのマイナーバージョン
（2.2.8以外は最新のタイニーバージョン）で同じ結果が得られました：

* 引数の順序はatime, mtime, filename
* filename複数指定は2つの場合のみ試したが、2つともタイムスタンプが更新されることを確認済み
* 指定したファイルがシンボリックリンクでない場合、シンボリックリンクのタイムスタンプも更新される
* 指定したファイルがシンボリックリンクの場合、元ファイルのタイムスタンプも更新される

.lutime()については、2.4以前がNoMethodエラー、2.5、2.6.0-preview2は同じ結果ですが、
.utime()との相違点として:

* 指定したファイルがシンボリックリンクの場合、元ファイルのタイムスタンプもシンボリックリンクのタイムスタンプも更新されない

となっています。

**Comment by nico-hn** [comment]
動作環境を報告し忘れていましたが、
utuntu 17.10
uname -a
Linux pc-VirtualBox 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
です。

**Comment by sho-h** [comment]
@nico-hn ありがとうございます！上記であれば分岐は不要そうなので #1433 で単純に順番を変えるなどしました。
