### ISSUE TITLE
Queue.newのサンプルの整形がおかしい

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#1464]
noexampleをsamplecodeで挟んでるからのようなのでnoexampleだけにする。

* https://docs.ruby-lang.org/ja/2.5.0/method/Thread=3a=3aQueue/s/new.html
* https://github.com/rurema/doctree/blob/fa0b1f2b4b2b1d820a322f401d182ec7ece5efba/refm/api/src/thread/Queue#L53-L55

**Comment by sho-h** [comment]
おぉ、展開されるようになったんですな...(楽ちんですけど、箇条書きとしては微妙ですな

**Comment by znz** [comment]
`#@samplecode` .. `#@end` とか `#@if` .. `#@end` とかで中身がない時に bitclust で警告が出ると良いのかも。
