### ISSUE TITLE
文字列を置き換えない場合のString#gsubとString#scanの違い

### ISSUE THREAD

**Issue by asm256** [rurema/doctree#1489]
https://docs.ruby-lang.org/ja/latest/method/String/i/gsub.html
> なお、ブロック付きの gsub で文字列を置き換えない場合はString#scan と同じ動作になります。

となっているが

[String#scan](https://docs.ruby-lang.org/ja/latest/method/String/i/scan.html)は
>  pattern が正規表現で括弧を含む場合は、 括弧で括られたパターンにマッチした文字列の配列を渡します。

が、行われるがgsubではそういう事が行われないので同じ動作とは言えないと思います

**Comment by sho-h** [comment]
gsubでそういう使い方されても読みにくいだけですので「なお、」以降削除でいい気がしますね。
