### ISSUE TITLE
Ruby 1.8.7, 1.9.3, 2.1.0 のページが混在コンテンツになっている

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#1514]
以下のページがいわゆる「混在コンテンツ」になっています。

https://docs.ruby-lang.org/ja/1.8.7/doc/
https://docs.ruby-lang.org/ja/1.9.3/doc/
https://docs.ruby-lang.org/ja/2.0.0/doc/

以下の記述が原因のようです。（ページは HTTPS なのに HTTP に link している）

```html
  <link rel="canonical" href="http://docs.ruby-lang.org/ja/latest/doc/index.html">
```

[トップページ](https://docs.ruby-lang.org/ja/) からリンクしている以上、直したほうがよいかと思いますが、どうやって直すのか分かりませんでした。

**Comment by znz** [comment]
https://github.com/ruby/docs.ruby-lang.org を見るとわかると思うのですが、 2.2.0 以前はもう生成し直していないので、直接 HTML を書き換えてもらうしかなさそうです。

**Comment by scivola** [comment]
混在コンテンツの問題は一度変換すれば再修正が必要になる可能性はないと思います。

しかし，このサイトで混在コンテンツであることがどのくらいどんなふうに良くないことなのか，正直言って分かりません。
判断はお任せします。

**Comment by sho-h** [comment]
もし具体的な問題があれば古いバージョンは公開をやめるのがいいと思ったのでcloseしちゃいます。
