### ISSUE TITLE
「値を返さない式」

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#1522]
「制御構造」に

> Rubyでは(Cなどとは異なり)制御構造は式であって、何らかの値を返すものが あります(返さないものもあります。値を返さない式を代入式の右辺に置くと syntax error になります)。 

とか

> Rubyの式には値を返す式と返さない式があります。
>
> 値を返さない式の例
>
> while 修飾式, until 修飾式

などとあります。

この「値を返さない式」というのが積年の謎でした（評価値を持たないのに式と呼べるの？）。
「while 修飾式」というのは「式を while 修飾したもの」、つまり，

> foo while bar

のようなものだと思いますが，これが値を持たなかったのは Ruby 1.6 の頃の話なのではないでしょうか。

同じページの「while 修飾子」のところには

>  while 修飾した式は nil を返します。 また、引数を伴った break により while 修飾した式の戻り値を その値にすることもできます。 

とあります。

until 修飾式も同様なので，結局，「例」が無くなってしまうのですが，Ruby 2.0 以降でも「値を返さない式」があるとすればどんなものでしょうか？

**Comment by pocke** [comment]
`return`や`break`、`next`が「値を返さない式」として書かれていると推測することができそうです(確信はないです)。
`_ = return` のようなプログラムはエラーとなります。

```ruby
# test.rb
_ = return
```

```bash
$ ruby -c test.rb
test.rb:2: void value expression
_ = return
    ^~~~~~
```

"void value expression"と言っているので、これは「値を返さない式」のことかなと思っています。

---


> Rubyの式には値を返す式と返さない式があります。
>
> 値を返さない式の例
>
> while 修飾式, until 修飾式

これは https://docs.ruby-lang.org/ja/latest/doc/spec=2fprogram.html このへんの記述ですかね。
while修飾式などが値を返すのはそのとおりのようなので、これは修正したほうが良さそうですね。

**Comment by scivola** [comment]
なるほど！　return , next, beak は評価値を考えることに意味がありませんものね。
これを式の仲間に入れるかどうかが問題ですが，式だということになっているのでしょうね，きっと。

修正はどのようにするのがよいでしょうか。
とりあえず，明らかな間違いを無くすだけであれば，

> 値を返さない式の例
> 
> while 修飾式, until 修飾式

の削除のみ，となるでしょうか。

理想的には，return，break，next など値を返さない式をすべて列挙するのがよさそうですが。

**Comment by pocke** [comment]
> これを式の仲間に入れるかどうかが問題ですが，式だということになっているのでしょうね，きっと。

ですね。。一般的にこういうのを式と言っていいのかはっきりわからないですが、エラーメッセージを見る限りだとRubyでは式だということになっているみたいですね。。


> 修正はどのようにするのがよいでしょうか。
> とりあえず，明らかな間違いを無くすだけであれば，
> 
>> 値を返さない式の例
>>
>> while 修飾式, until 修飾式
>
> の削除のみ，となるでしょうか。
>
> 理想的には，return，break，next など値を返さない式をすべて列挙するのがよさそうですが。



そうですね、私は単に削除してしまっても良いような気がします。

列挙するなら、`return`, `break`, `next`, `redo`, `retry` ぐらいで全部かな、と思いますが自信はないです。
もしくは「`return`, `break`, `next`など」と書いてしまっても良いかなと思います。それだけで「こういう式が値を返さない式なのかー」とイメージはつくとおもいます。
