### ISSUE TITLE
SampleCodeGuideline に RDoc の参照の仕方を書く

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#1550]
Wiki の SampleCodeGuideline の末尾に「RDocとの関係」があるのですが，RDoc が何なのかよく分からない（ドキュメントフォーマットの名前だと思ってました）のと，目的のメソッドの RDoc をどうやって探したらよいのか分からなかったので，簡単に書いていただけるとありがたいです。

**Comment by tbpgr** [comment]
更新してみました。

![_110218_032930_am](https://user-images.githubusercontent.com/4787509/47879846-044cb800-de65-11e8-9af8-62e4e08c2be3.jpg)

* [SampleCodeGuideline · rurema/doctree Wiki](https://github.com/rurema/doctree/wiki/SampleCodeGuideline)

**Comment by scivola** [comment]
ありがとうございました。
これだけ分かれば十分です。
