### ISSUE TITLE
matrix ライブラリーの例外が二重に記述されている

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#1561]
以下の三つの例外クラスは `refm/api/src/matrix/Matrix` に記述されているにも関わらず，`refm/api/src/matrix/Vector` にも記述されています。

* ExceptionForMatrix::ErrDimensionMismatch
* ExceptionForMatrix::ErrNotRegular
* ExceptionForMatrix::ErrOperationNotDefined

`Vector` のほうは

```rd
= class ExceptionForMatrix::ErrDimensionMismatch < StandardError
= class ExceptionForMatrix::ErrNotRegular < StandardError
= class ExceptionForMatrix::ErrOperationNotDefined < StandardError
```

のように中身が無く `=` の行だけになっており，そのせいなのか変換できずに以下の例外が発生します。

```
XXXXX/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bitclust-core-1.2.1/lib/bitclust/classentry.rb:396:in `description': undefined method `strip' for nil:NilClass (NoMethodError)
```

この 3 行を削除すれば変換は成功します。

プルリクエスト #1556 と #1557 で  The Travis CI build failed が出ているのは，これのせいではないかと思います。
（`Failed to bitclust htmlfile, ruby: 2.3.0, target: ExceptionForMatrix::ErrDimensionMismatch, path: refm/api/src/matrix/Vector` なので）

しかし，上記 3 行を単純に削除してしまってよいのか判断がつきません。

**Comment by sho-h** [comment]
83d7f0ae5 と 05a985b09 を見るに昔は別々のクラスだったようですね。matrix.rd に移動しました。
