### ISSUE TITLE
&&, || の定義が不十分

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#159]
&&, ||, and, or を用いた式の評価結果がどうなるかは「演算子式」の「and」「or」の項にしか書かれていないようです。

http://docs.ruby-lang.org/ja/2.2.0/doc/spec=2foperator.html#and
http://docs.ruby-lang.org/ja/2.2.0/doc/spec=2foperator.html#or

しかし，これでは結果の真／偽がどうなるかは分かっても，評価結果が具体的にどのようなオブジェクトになるのかが分かりません。

試した限りでは

* `exp1 || exp2` の評価結果は，`exp1` の評価結果が真ならそれになり，偽なら `exp2` の評価結果になる
* `exp1 && exp2` の評価結果は，`exp1` の評価結果が偽ならそれになり，真なら `exp2` の評価結果になる

ようなのですが，これが Ruby の仕様なのかどうか確認できればと思います。

**Comment by ohai** [comment]
|| のほうはこの機能が活用される場面があるので仕様であることはほぼ間違いないと思います。
   
       @x ||= 0   # @x = @x || 0 と同じ

のようなイディオムはしばしば使われます。

&&のほうは真偽値しか使わないことが大半ですが対称性からおそらく仕様だとは思いますし、両方適当に直すことにしましょうか。

**Comment by scivola** [comment]
いま気づきましたが，どうも JIS X 3017 に書いてあるみたいです。どの箇所かというのはちょっとその。

それと，`&&` のほうですが，どうも世間には `式1 if 式2` の代わりに `式2 && 式1` と書く人たちがいるようでして。

rubocop さんも

```rb
if 式1
  式2
end
```

を見ると，

> Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.

と仰るので，少なくともそういう `&&` が悪いものとは見てないようです。
