### ISSUE TITLE
library zlibの@seeがデットリンク

### ISSUE THREAD

**Issue by takiy33** [rurema/doctree#160]
[library zlib](http://docs.ruby-lang.org/ja/2.2.0/library/zlib.html)の「@see zlib(3)」がデットリンクになっています。

**Comment by ohai** [comment]
http://zlib.net にリンクしたほうがよいですかねえ

**Comment by takiy33** [comment]
@ohai ご回答ありがとうございました。プルリクエストを作成しました。
