### ISSUE TITLE
Date.json_create が NoMethodError になる

### ISSUE THREAD

**Issue by tbpgr** [rurema/doctree#1649]
* [library json/add/core (Ruby 2.5.0)](https://docs.ruby-lang.org/ja/latest/library/json=2fadd=2fcore.html)

のサンプルコードを作ろうとして、以下のコードを実行したところ、 NoMethodError になりました。

```ruby
require "json"
require "date"

Date.json_create({ y: 2018, m: 12, d: 10 })
# => undefined method `json_create' for Date:Class (NoMethodError)
```

なにか実行方法の誤りなどありますでしょうか？

## 参考資料
* [ruby/date.rb at 4444025d16ae1a586eee6a0ac9bdd09e33833f3c · ruby/ruby](https://github.com/ruby/ruby/blob/4444025d16ae1a586eee6a0ac9bdd09e33833f3c/ext/json/lib/json/add/date.rb#L11-L13)

**Comment by yui-knk** [comment]
明示的に `'json/add/date'` もしくは `'json/add/core'` をrequireする必要があると思います:

```ruby
require "json"
require "date"

d = Date.new(2017, 2, 4)
p d

puts "\n---without json add---\n"
json = JSON.generate(Date.new(2017, 2, 4))
p json
p JSON.parse(json)
p Date.json_create({ y: 2018, m: 12, d: 10 }) rescue (p $!)

puts "\n---with json add---\n"
require 'json/add/date'
json = JSON.generate(Date.new(2017, 2, 4))
p json
p JSON.parse(json)
p JSON.parse(json, create_additions: true)
p Date.json_create({ y: 2018, m: 12, d: 10 }) rescue (p $!)
```

```shell
$ ruby -v   /tmp/json.rb
ruby 2.6.0rc1 (2018-12-06 trunk 66253) [x86_64-darwin17]
#<Date: 2017-02-04 ((2457789j,0s,0n),+0s,2299161j)>

---without json add---
"\"2017-02-04\""
"2017-02-04"
#<NoMethodError: undefined method `json_create' for Date:Class
Did you mean?  json_creatable?>

---with json add---
"{\"json_class\":\"Date\",\"y\":2017,\"m\":2,\"d\":4,\"sg\":2299161.0}"
{"json_class"=>"Date", "y"=>2017, "m"=>2, "d"=>4, "sg"=>2299161.0}
#<Date: 2017-02-04 ((2457789j,0s,0n),+0s,2299161j)>
#<TypeError: no implicit conversion to float from nil>
```

また、https://github.com/flori/json#more-examples をみたところ`json_create`はdeserialize時に使用されるメソッドのようです。なので`Date.json_create`の形で開発者がコードを書くことは少ないのではないでしょうか。
また引数のhashはkeyがstringであることが期待されているようです。

```ruby
Date.json_create({ 'y' => 2018, 'm' => 12, 'd' => 10, 'sg' => 2299161.0 })
#=> #<Date: 2018-12-10 ((2458463j,0s,0n),+0s,2299161j)>
```

**Comment by tbpgr** [comment]
ありがとうございます。よくわかりました。

サンプルコードの観点でいうと、

> `json_create` はdeserialize時に使用されるメソッドのようです。なので `Date.json_create` の形で開発者がコードを書くことは少ないのではないでしょうか。

ということなので、 `noexample` の目印だけつけて、サンプルコード自体は作成しない方向でよいかなと思いました。問題なければ、サンプルコードの作成の取り組みとしては `noexample` にしようかと思います。

※実際に利用例を検索してみましたが、見当たらなかったので使われていないだろうと思いました

@sho-h 通知です。問題なさそうなら Issue としてはクローズで大丈夫です。

**Comment by sho-h** [comment]
> 問題なさそうなら Issue としてはクローズで大丈夫です。

サンプルとしてはcloseでいいのではないかと思います。リンクしていただいてるオリジナルのレポジトリのREADMEの記述がjsonライブラリの頭に欲しい気がしますがそれは別Issueにするのがよさそうですね。
