### ISSUE TITLE
Ruby 2.2.0 の library fiddle の dl へのリンクがデッドリンク

### ISSUE THREAD

**Issue by tbpgr** [rurema/doctree#166]
Ruby 2.2.0 の[library fiddle](http://docs.ruby-lang.org/ja/2.2.0/library/fiddle.html)の「dl」へのリンク（2箇所）がデッドリンクになっています。

**Comment by cielavenir** [comment]
リンクを直すというよりは削除するべきですね。
http://docs.ruby-lang.org/ja/2.1.0/library/dl.html
には「2.2.0で削除」と記述があるので。
ただ、2.2.0のfiddleのページに「dl は 2.0 以降deprecated」とありますが、2.2で削除された旨を記したほうが親切ですかね。

**Comment by sho-h** [comment]
おぉ、ありがとうございます。 @cielavenir さんの仰る通りですね。後で直しておきます。

**Comment by tbpgr** [comment]
ご確認ありがとうございます。 :smile:
