### ISSUE TITLE
Prime.prime? に負数を与えたとき偽を返すとは限らない

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#167]
http://docs.ruby-lang.org/ja/2.2.0/class/Prime.html#I_PRIME--3F

の `Prime.prime?` の説明に

> 引数 value に負の数を指定した場合は常に false を返します。

とあるのですが，引数が負だと符号を変えているので， `Prime.prime?(-17)` は `true` になります。

**Comment by sho-h** [comment]
これは2.2.0からは負の数を引数に与えると必ずfalseを返す修正のためですね。分岐を最近追加しました。

* http://docs.ruby-lang.org/ja/2.1.0/method/Prime/i/prime=3f.html
* http://docs.ruby-lang.org/ja/2.2.0/method/Prime/i/prime=3f.html

**Comment by scivola** [comment]
よく確認せずに書いてしまい，すみませんでした。

**Comment by sho-h** [comment]
全然問題ないです！
