### ISSUE TITLE
名前付きキャプチャーの値を取る MatchData#[name] の name は文字列も可

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#169]
`MatchData#[]` の `self[name]` 形式で，`name` について「名前(シンボル) 」となっています。

http://docs.ruby-lang.org/ja/2.2.0/method/MatchData/i/=5b=5d.html

しかし，Symbol のほか，String でもいいようです。

`MatchData#names` が String の配列を返すので，このことは重要です。

**Comment by sho-h** [comment]
ありがとうございます。以下を見るにその通りでしたので修正しました。

* https://github.com/ruby/ruby/blob/v2_2_0/re.c#L1805-L1809

また、MatchData#namesの戻り値も[Array]になってましたので[String]に修正しました。
