### ISSUE TITLE
Module#class_variablesに引数についての記載がない

### ISSUE THREAD

**Issue by takiy33** [rurema/doctree#171]
rdocには引数について説明がありますが、るりまのほうにはありません。

[http://docs.ruby-lang.org/ja/2.2.0/method/Module/i/class_variables.html](http://docs.ruby-lang.org/ja/2.2.0/method/Module/i/class_variables.html)
[http://www.ruby-doc.org/core-2.2.0/Module.html#method-i-class_variables](http://www.ruby-doc.org/core-2.2.0/Module.html#method-i-class_variables)

**Comment by sho-h** [comment]
ありがとうございます。以下だったみたいですね。修正しました。

* 2.0.0 〜: inheritで指定できるようになった
* 1.9.1 〜 1.9.3: inherit = falseと同じ
* 1.8.7: 全て返す

**Comment by takiy33** [comment]
ご対応頂き、ありがとうございました。
