### ISSUE TITLE
Struct.newのメソッド定義について

### ISSUE THREAD

**Issue by takiy33** [rurema/doctree#178]
「[RubyのStructのイディオムとアンドキュメンテッドな機能](http://d.hatena.ne.jp/yarb/20130104/p1)」という記事でStruct.new時にメソッド定義を出来ることがアンドキュメンテッドと記載されていました。

**Comment by sho-h** [comment]
あ、まだなかったんですね...ありがとうございます。今はあるみたいですので足しておきます。

* http://docs.ruby-lang.org/en/trunk/Struct.html

**Comment by takiy33** [comment]
ご対応ありがとうございました。
