### ISSUE TITLE
検索エンジン対策 - HTML titleにリファレンスマニュアルであることを明記する

### ISSUE THREAD

**Issue by JunichiIto** [rurema/doctree#2036]
現状のHTML titleは以下のように出力されています。

```html
<title>instance method Array#compact (Ruby 2.6.0)</title>
```

これを以下のように変更するとSEOが改善するかもしれません。

```html
<title>instance method Array#compact (Ruby 2.6.0 リファレンスマニュアル)</title>
```

というのは、 https://ref.xaio.jp/ruby/classes/array/compact を見ると、

```html
<title>compact, compact! (Array) - Rubyリファレンス</title>
```

のように「Rubyリファレンス」という文言が含まれているからです。

この点で ref.xaio.jp とSEOで差が付けられているのかもしれない、と推測しました。

PRも作ってみました。

https://github.com/rurema/bitclust/pull/78

**Comment by hanachin** [comment]
こちらbitclustの方で修整されていて、docs.ruby-lang.orgのほうに反映されているので、閉じます
