### ISSUE TITLE
PRの変更をオンラインでレビューできる仕組みが欲しい

### ISSUE THREAD

**Issue by pocke** [rurema/doctree#2053]
# ほしい物

PRをレビューするさいに実際に変更されたHTMLを見るには手元でfetchしてビルドする必要があってちょっと大変なので、オンラインでそれを確認できるものがほしい

# 解決策

Netlifyを使うと手軽に実現できそう

https://twitter.com/zundan/status/1206396995058855936

# 他の案

* Heroku Review Apps
  * 課金しないとつらそう
  * 動的Webページがメインターゲットなのでオーバースペックかも
* CircleCI Artifact
  * 使ったことがないからわからない…
* GitHub Actions
  * 仕組みはありそうだけど使ったことがないからわからない

# 不安要素

* Netlifyでホストされるページでは検索避けをしないと、本番の docs.ruby-lang.org の検索順位が下がってしまいそう？

**Comment by hanachin** [comment]
doctreeのレビューもそうですがbitclustの方でHTMLのデータ構造を変えたときもオンラインレビューできると確認が楽そうなので、bitclustの方にもほしいですね

**Comment by pocke** [comment]
resolved by #2062

**Comment by znz** [comment]
- [meta-robots-content](https://github.com/ruby/docs.ruby-lang.org/blob/7590881cca022f3b50ea010890aecb9453485340/system/bc-static-all#L32) のデフォルトが `noindex` なので、ロボット避けは大丈夫そうです。
- `--canonical-base-url` も localhost をさしておく意味はないので、ローカル生成も含めて `Rakefile` でのデフォルトを変更しました。
- 以前試した時に netlify は `/tmp` 以下のファイルの publish がうまくいかなかった覚えがあるので、 `HTML_DIRECTORY_BASE` を指定できるようにしました。
- 以前試した時に netlify で複数バージョン生成すると時間切れで失敗していた覚えがあるので、 2.6.0 だけにしています。
