### ISSUE TITLE
最新版以外のページを検索結果に出ないようにしたい

### ISSUE THREAD

**Issue by zonuexe** [rurema/doctree#206]
## 現状

現在日本語でRuby関連用語を検索したとき、多くは以下のような検索結果になります。

<img width="1002" alt="検索結果" src="https://cloud.githubusercontent.com/assets/822086/8958701/40a689f4-3641-11e5-886c-5ae4c08747d1.png">

不幸なことに1.8.7は既にメンテナンス終了して居り、情報を求める利用者に旧バージョンの情報を見せることは良い状態ではありません。

## 提案

`http://docs.ruby-lang.org/ja/`のコンテンツについて、URLにバージョン番号が含まれるページについて、canonical属性を使ったURL正規化を行ってください。

`class URI::Generic`の記事であれば、最新版の2.2.0を含めて5バージョンあることになります。

* http://docs.ruby-lang.org/ja/1.8.7/class/URI=3a=3aGeneric.html
* http://docs.ruby-lang.org/ja/1.9.3/class/URI=3a=3aGeneric.html
* http://docs.ruby-lang.org/ja/2.0.0/class/URI=3a=3aGeneric.html
* http://docs.ruby-lang.org/ja/2.1.0/class/URI=3a=3aGeneric.html

最新版 **以外** のHTMLの`head`要素内に以下のようなタグを記述してください。`href`の参照先は同じ記事の最新版のURLです。

```html
<link rel="canonical" href="http://docs.ruby-lang.org/ja/2.2.0/class/URI=3a=3aGeneric.html">
```

すると、Googleなどの検索エンジンは最新版のページを優先して検索結果に表示してくれるようになることが期待できます。

## 情報

URLの正規化については以下のページを参照してください。

 * [canonical属性とは／link rel="canonical"によるURL正規化タグ——SEOにとって非常に重要な進歩（前編） | Moz - SEOとインバウンドマーケティングの実践情報 | Web担当者Forum](http://web-tan.forum.impressrd.jp/e/2009/03/05/5112)
 * [<link rel=”canonical”>（カノニカルタグ）の使い方 - SEOのホワイトハットジャパン](http://whitehatseo.jp/%E3%82%AB%E3%83%8E%E3%83%8B%E3%82%AB%E3%83%AB%E3%82%BF%E3%82%B0%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6url%E3%82%92%E6%AD%A3%E8%A6%8F%E5%8C%96%E3%81%95%E3%81%9B%E3%82%8B%E6%96%B9%E6%B3%95/)

**Comment by sho-h** [comment]
これはバージョン決め打ちで検索したい場合はどういう風に検索する想定のご提案なんでしょう？

あと[るりまサーチ](http://docs.ruby-lang.org/ja/search/)とか使うのではダメですか？

**Comment by zonuexe** [comment]
バージョン絞りこみこそるりまサーチの機能ではないでしょうか。
http://docs.ruby-lang.org/ja/search/query:URI%3A%3AGeneric/version:1.8.7/

それよりも廃止済みバージョンの情報が(るりまサーチなど利用しない、Googleなどから訪れる)一般ユーザーの目に触れるデメリットの方が大きいかと存じます。

**Comment by sho-h** [comment]
えーっと...それだと議論にならないので、では一旦るりまサーチの話は取り下げます。

質問を変えると一般ユーザさんはどのような検索語を指定する想定でどのような結果になる想定でしょうか？ただ廃止になっているバージョンを除外したいなら、検索フォームで頑張ってくださいと思いました。検索の内容によってたとえば2.1と2.2の微妙な違いなど検索仕分けられるのであれば検討してもいいんじゃないかと思います。

**Comment by okkez** [comment]
Googleなどの検索結果に旧バージョンのものが出てしまうのが、あまり詳しくない人(最新バージョンがいくつなのか把握していない人)を混乱させるのではないか？という問題提起だと理解しました。
なので、Googleなどの検索結果にはなるべく最新版だけが出るようにしたい、ということでしょうか。

**Comment by zonuexe** [comment]
@okkez はい、その通りです。

**Comment by nurse** [comment]
@zonuexe さんに賛成で、無指定時のデフォルトが古いバージョンに誘導されがちなのはよくないと思います。加えて、正規化先はのURLはバージョン無しの方が長期的に見て良いと思いました。

という感じで適当に権限調達して何とかしようと思うんですが、何か意見のある方はいますでしょうか

**Comment by sho-h** [comment]
以下が気になってました、やった方がよくなるのはどの道間違いないと思っていますのでやってくださる方がいるのであれば方法は問わず反対はしません。

- 特定の検索方法を強制しない
- 1.8.7 〜 2.0.0のような既に更新を停止したインデックスも作業せずに問題なく誘導できる
  - 最新版が変わる度に生成し直しが発生しない

**Comment by nurse** [comment]
とりあえず

```
        location /ja/doc {
            alias /var/www/docs.ruby-lang.org/current/ja/2.3.0;
        }
```
を追加しました。cannonical指定するのはbitclustの方かな?

**Comment by sho-h** [comment]
> cannonical指定するのはbitclustの方かな?

ですね。

**Comment by okkez** [comment]
2.0.0以前のやつは、もう更新していないはずなのでそちらもどうにかしないといけません。。。
bitclustに機能を追加してデプロイしても自動では追従できないという問題があります。

**Comment by okkez** [comment]
`bitclust statichtml --canonical-base-url` というオプションを実装して0.9.2をリリースしました。
https://github.com/ruby/docs.ruby-lang.org/pull/20 で新機能のデプロイを依頼中です。

2.0.0 以前のやつはスクリプトで直接、書き換えてしまうのがよさそうです。

**Comment by hsbt** [comment]
deploy も含めて、やってみます!

**Comment by hsbt** [comment]
デプロイと、bitclust-0.9.2 への更新をやっておきました。数日後に状況などを確認して足りてない部分があったらご連絡ください。

**Comment by okkez** [comment]
2.0.0 以前のやつも canonical 足しときました。

**Comment by okkez** [comment]
検索結果を見てると、ぼちぼち canonical の効果が出始めていそう。

**Comment by okkez** [comment]
効果出始めているのを確認したので閉じます。

**Comment by zonuexe** [comment]
このまま順調に行けば大丈夫そうです。ありがとうございます。 🙇 

https://www.google.co.jp/search?q=URI%3A%3AGeneric

**Comment by hsbt** [comment]
2016/10 に *.ruby-lang.org の証明書更新の作業を行う予定なので、その機会に docs.r-l.o も https にしてより SEO に有利になるようにしていきます。

**Comment by okkez** [comment]
よろしくお願いします :pray:
