### ISSUE TITLE
「library bigdecimal/util」のパンくずリストのデザインが崩れていました

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2100]
https://docs.ruby-lang.org/ja/2.5.0/library/bigdecimal=2futil.html のページで、パンくずリストのデザインが崩れていました。

<img width="1336" alt="xxx" src="https://user-images.githubusercontent.com/3800237/72119174-ce735f80-3396-11ea-9f9d-7957a5fb54d0.png">

**Comment by taki** [comment]
リロードしたところ、私のブラウザが原因のようでしたのでクローズします。

**Comment by hanachin** [comment]
CSSのキャッシュが残っていると崩れて見えることがありそうですね、報告ありがとうございました :pray:
