### ISSUE TITLE
「Array.try_convert」ページの rdoc へのリンクが 404 になる

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2106]
https://docs.ruby-lang.org/ja/master/method/Array/s/try_convert.html から「rdoc」をクリックしたところ404になりました。

**Comment by znz** [comment]
報告ありがとうございます。
`/en/2.8.0/` から `/en/master/` へのリダイレクトを追加して対応しました。

**Comment by taki** [comment]
なるほど、なるほど。対応ありがとうございました 🙏
