### ISSUE TITLE
非推奨になったことはバージョン分岐なしで表示したほうが良い？

### ISSUE THREAD

**Issue by pocke** [rurema/doctree#2118]
# Problem

メソッドなどが非推奨になった時、現在は非推奨になったバージョンで分岐して表示しています。

例:

```
Object#taint

#@since 2.7.0
このメソッドは2.7から非推奨になりました
#@end
```

このように書くと、当然ながら2.7以上のドキュメントにしか`Object#taint`が非推奨になったことは表示されません。
ですが、「新しいバージョンで非推奨になると分かっている機能」は古いバージョンでも使うのを避けられるなら避けたほうが良いと思います。
ですが現状だと古いバージョンのドキュメントには非推奨になった事実は表示されないので、非推奨であることに気が付かず機能を使ってしまって後から書き直す必要が出てくる可能性があります。

# Solution

メソッドが非推奨になったことはバージョン分岐なしで記述することを提案します。
つまり上の例だと、次のようになるイメージです。

```
Object#taint

このメソッドは2.7から非推奨になりました
```

---

こちらのほうがより親切かなと思うのですが、どうでしょうか？

**Comment by scivola** [comment]
以前からそのように考えていました。
ただ，バージョン表記は「2.7」よりも「Ruby 2.7」のほうがよいと思います。
数字だけなど，何の数字かすぐにピンとこない場合がありそうですし，gem で配布されるライブラリーが多くなって gem のバージョンと紛らわしい場合も出てきそうだからです。
