### ISSUE TITLE
Range に to_a が見つからない（継承されたメソッドのエイリアスの問題）

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#2125]
Range のページ
https://docs.ruby-lang.org/ja/2.7.0/class/Range.html
の「Enumerableから継承しているメソッド」のところに `to_a` があるかと思ったら，ありませんでした。
どうやら，`Enumerable#to_a` は無くて，エイリアスの関係にある `Enumerable#entries` だけが挙がっているようです。
両方載せることはできないでしょうか。

`(1..3).to_a` を見た初心者がリファレンスの当該箇所に行き着くのはちょっと難しいのではないかと思います。

**Comment by pocke** [comment]
Enumerableのページにはentriesもto_aも両方目次に表示されているので、表示させることはできそうな気がしますね。
https://docs.ruby-lang.org/ja/2.7.0/class/Enumerable.html


bitclust側で対応が必要かな🤔
