### ISSUE TITLE
library did_you_meanのプロジェクトページの修正

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [rurema/doctree#2130]
did_you_maenのプロジェクトページのリンクが[https://docs.ruby-lang.org/ja/latest/library/did_you_mean.html](https://docs.ruby-lang.org/ja/latest/library/did_you_mean.html)となっていますが、現在では[https://github.com/ruby/did_you_mean](https://github.com/ruby/did_you_mean)へとリダイレクトされているようです。

現状でもとりあえずは問題がないとは思いますが、念のため[https://github.com/ruby/did_you_mean](https://github.com/ruby/did_you_mean)に修正したほうがよいかと思っています。
いかがでしょうか？

**Comment by pocke** [comment]
https://github.com/yuki24/did_you_mean を https://github.com/ruby/did_you_mean に修正するということでしょうか？良いと思います！

**Comment by S-H-GAMELINKS** [comment]
そういう感じですねー

では、合間にPR作って投げておきますね！
