### ISSUE TITLE
quote_char

### ISSUE THREAD

**Issue by huifangW** [rurema/doctree#2152]
https://docs.ruby-lang.org/ja/latest/method/CSV/i/quote_char.html

**Comment by pocke** [comment]
@huifangW 
quote_char のドキュメントをどう修正したいのか、詳細を書いてもらえるでしょうか？

**Comment by pocke** [comment]
こちら特に返信がないのでcloseします。
何かあったらIssueを立て直すかこのIssueにコメントください🙏
