### ISSUE TITLE
class Zlib::Error にて箇条書きのフォーマットが崩れている

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2175]
https://docs.ruby-lang.org/ja/master/class/Zlib=3a=3aError.html にて、以下のように箇条書きのフォーマットが崩れているみたいです。

![xxx](https://user-images.githubusercontent.com/3800237/74959310-abd06e00-544d-11ea-9be7-62b98c205e8a.png)

**Comment by pocke** [comment]
#2176 で修正されたのでcloseします。報告ありがとうございました🙏
