### ISSUE TITLE
constant Date::ENGLAND の see also のリンクが切れている

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2178]
https://docs.ruby-lang.org/ja/2.7.0/method/Date/c/ENGLAND.html の中で http://www.cs.bell-labs.com/who/dmr/man61.pdf へのリンクが切れているようです。

**Comment by scivola** [comment]
www.cs.bell-labs.com というホストが既に存在しておらず，[Internet Archive](https://web.archive.org/) にも見当たりませんね。
単純削除でいいような気がします。

**Comment by elim** [comment]
おそらくこの PDF だと思います <https://www.bell-labs.com/usr/dmr/www/pdfs/man61.pdf>

**Comment by elim** [comment]
[Internet Archive](https://web.archive.org/) でも見つけられました。

（ `http://cm.bell-labs.com/cm/cs/who/dmr/pdfs/man61.pdf` を検索しても見つからなかったのですが、 `http://cm.bell-labs.com/cm/cs/who/dmr/` を検索して、保存されていたページから辿ることができました。）

<https://web.archive.org/web/20150205025957/http://cm.bell-labs.com/cm/cs/who/dmr/pdfs/man61.pdf>

<https://www.bell-labs.com/usr/dmr/www/pdfs/man61.pdf> と md5 値が一致するようです

* * *

<https://www.bell-labs.com/usr/dmr/www/pdfs/man61.pdf> はデニス・リッチーのページから辿れますし、資料的価値からいっても「なにかの拍子に消されてしまう」ということも（当面は）ないのではないかなあと思います。

* [Dennis Ritchie Home Page](https://www.bell-labs.com/usr/dmr/www/) から [Unix Programmer's Manual, First Edition (1971)](https://www.bell-labs.com/usr/dmr/www/1stEdman.html) へ遷移
* [Unix Programmer's Manual, First Edition (1971)](https://www.bell-labs.com/usr/dmr/www/1stEdman.html) から [man61.pdf](https://www.bell-labs.com/usr/dmr/www/pdfs/man61.pdf) を開く

ということで、 rurima からのリンク先も、現在の URL に差し替えてはどうでしょう。

**Comment by taki** [comment]
コメントありがとうございます。そんなところにあったのですね。#2204 をリンク先の対応に変更しました。
