### ISSUE TITLE
tr に全角英数字の半角化の例を追加

### ISSUE THREAD

**Issue by znz** [rurema/doctree#2210]
> 大文字化よりも，全角英数字の半角化 `tr("０-９ａ-ｚＡ-Ｚ", "0-9a-zA-Z")` のほうが，①実用性（現実味），②範囲が複数書けることのシンプルな例，という面で良いように思います。が，これも説明文に入れるよりはサンプルコードに入れればいいと思います。

_Originally posted by @scivola in https://github.com/rurema/doctree/pull/2150#issuecomment-586082646_

**Comment by hanachin** [comment]
#2238 で追加されたのでcloseします
