### ISSUE TITLE
String#split(nil)の挙動が実際と異なる

### ISSUE THREAD

**Issue by yugui** [rurema/doctree#222]
http://docs.ruby-lang.org/ja/2.2.0/method/String/i/split.html には
> 1 バイトの空白文字 ' ' か nil
> 先頭と末尾の空白を除いたうえで、空白文字列で分割する。

と書かれています。しかし実際にはhttps://bugs.ruby-lang.org/issues/11729 で報告されているように、`String#split(nil)`は常に`String#split($;)`として動作します。その上で`$; == nil`の場合には書かれているような動作をします。

**Comment by okkez** [comment]
ありがとうざいます :bow:
