### ISSUE TITLE
Complexには `>` というメソッドはなさそうです

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2241]
https://docs.ruby-lang.org/ja/2.7.0/class/Complex.html のページには「Comparableから継承しているメソッド」として紹介されていますが、以下のようにComplexには存在しないメソッドのようです。

```console
irb(main):001:0> (2 + 3i) > (3 + 2i)
Traceback (most recent call last):
        4: from /Users/y.takizawa/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        3: from /Users/y.takizawa/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        2: from /Users/y.takizawa/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NoMethodError (undefined method `>' for (2+3i):Complex
```

**Comment by scivola** [comment]
「継承しているメソッド」に掲載されているのは，Complex のスーパークラスである Numeric に Comparable モジュールが include されているからだと思いますが，Complex では（`>` に限らず）Comparable のメソッドを未定義にしているんですよね。
どうやって直したらいいのか私にはわかりません。

同じことが Module クラスと Class クラスの間にも言えそうですが，[Class](https://docs.ruby-lang.org/ja/2.7.0/class/Class.html) のページには，未定義にされている Module のメソッド（`module_function` など）は載っていないんですよね。

**Comment by taki** [comment]
うーむ、なかなか解決は難しそうですね。

**Comment by znz** [comment]
bitclust の方で undef 対応をして doctree 側で undef されたメソッドを記述できるようにする必要がありそうです。

**Comment by scivola** [comment]
`Class` にはどうして `Module#module_function` が載っていないんだろう？

**Comment by hanachin** [comment]
> `Class` にはどうして `Module#module_function` が載っていないんだろう？

@scivola このissueは #2348 のマージで閉じられたので `Module#module_function` についてのissueがまだあれば別途たててもらえると助かります :pray:
