### ISSUE TITLE
Module#freeze の例外クラスが RuntimeError のままになっていました

### ISSUE THREAD

**Issue by dishrag** [rurema/doctree#2250]
Module#freeze ページ内に記載の例外クラスが RuntimeError のままになっている旨を
見つけましたのでご報告させていただきました。

該当:
Ruby 2.5 以降の Module#freeze ページ
https://docs.ruby-lang.org/ja/2.5.0/method/Module/i/freeze.html
https://docs.ruby-lang.org/ja/2.6.0/method/Module/i/freeze.html
https://docs.ruby-lang.org/ja/latest/method/Module/i/freeze.html
https://docs.ruby-lang.org/ja/master/method/Module/i/freeze.html

補足:
・サンプルコードは等しく FrozenError に更新されていました
・Object#freeze は概説･サンプルコードいずれも FrozenError に更新されていました

※報告時の慣習を誤っていましたら申し訳ありません（人生初Issueです）

**Comment by pocke** [comment]
Issue報告ありがとうございます！


https://github.com/rurema/doctree/blob/8cd48a6a5e40876effa0ca1a14591bcd577329cd/refm/api/src/_builtin/Module#L706

この辺を直すと良さそうです。もしよかったらPull Requestを作るのにもチャレンジしてください🙏


> ※報告時の慣習を誤っていましたら申し訳ありません（人生初Issueです）


問題の箇所と、どうなっているべきかがわかってバッチリなIssueだと思います👍
