### ISSUE TITLE
faq/ を削除したい

### ISSUE THREAD

**Issue by pocke** [rurema/doctree#2266]
# Problem

このリポジトリには `faq/`ディレクトリがあります。どうやらこれは旧リファレンスマニュアルから持ってきた内容のようです。
また、 docs.ruby-lang.org/ja では利用されていなさそうです。もしどこかで使われていたら教えてください。

> 旧リファレンスマニュアルの、Ruby FAQのデータのコピーです。いまのところ、Webからは見られません。
> https://github.com/rurema/doctree/wiki/Tutorial

`faq/`ディレクトリ下はメンテされていません。どのくらいメンテされていないかと言うと、2006年のfirst commitを含めて4コミットしかなく、最終更新日は2017年です。
https://github.com/rurema/doctree/commits/master/faq

軽く眺めただけでもすでに古くなった内容はたくさん見つかりました。

# Solution

`faq/`ディレクトリ下を削除することを提案します。

このディレクトリは現状のるりまでは使われていないため、このリポジトリにあることは混乱を招くと思います。実際私もドキュメントの修正をする際に「このディレクトリの内容は更新すべきなのだろうか」と調べたことは何回かあります。

ディレクトリを削除すればそのような混乱を回避できます。また、`git grep`による検索からノイズを削れます。

---

ただ、歴史的資料として残しておきたいなとは思うので、別リポジトリを作成して、そちらに`faq/`下のファイルを移すのはどうでしょうか？
READMEなどにメンテされていないことを明示することで、どのような立ち位置の文書群なのかも説明がしやすくなります。
また、将来的にfaqをるりまのコンテンツとして作成したくなった際も、参照しやすくなると思います。大幅な書き直しは必要になると思いますが。。

別リポジトリを作る場合、リポジトリ名は`rurema/faq`か、`rurema/old_documents`のようなものが良いかと考えています。
前者にはfaqディレクトリ下のものをそのまま移すことを想定しています。
後者であれば、rurema/doctree内の他の古くなったドキュメント類を移す場所としても使えそうです。

**Comment by scivola** [comment]
別リポジトリーに移す案に賛成です。
faq/ の内容は，もし編集し直せるなら有用なので，将来のリバイバルを期待して別リポジトリーに切り離したうえで残しておきたい。

よく分かっていませんが，refm/old/ も同様の扱いができるのではないでしょうか。

また，[Marshal](https://docs.ruby-lang.org/ja/2.7.0/doc/marshal_format.html) は公開ページですがとても古いので（ https://github.com/rurema/doctree/issues/2199 ），もしいったん公開をやめるのであれば，やはり同じ扱いがよさそうです。

以上から，faq/ だけでなく，その手のものをまとめて置いておくリポジトリーとするのを推したいと思います。

**Comment by pocke** [comment]
> よく分かっていませんが，refm/old/ も同様の扱いができるのではないでしょうか。




なるほど、refm/old/ の存在を知りませんでした。
軽く見た感じでは、同様の扱いができそうに見えますね。リポジトリを作るときは考慮したいですね


> 以上から，faq/ だけでなく，その手のものをまとめて置いておくリポジトリーとするのを推したいと思います。

:+1:

**Comment by znz** [comment]
古いドキュメントとして分離してしまうのに賛成です。

Ruby/Tk のように default gem や bundled gem としても残っていなくて外されたものも移動できると良さそうです。

最近外されたものだと mathn も移動しても良いのかもしれません。

```
% docker run -it --rm rubylang/all-ruby env ALL_RUBY_SINCE=ruby-2.0 ./all-ruby -e 'begin;require "mathn";rescue LoadError;p($!.class);end'
ruby-2.0.0-p0
...
ruby-2.4.10
ruby-2.5.0-preview1 LoadError
...
ruby-2.7.1          LoadError
```

**Comment by pocke** [comment]
コメントありがとうございます〜



もらったコメントを元に、なぜfaqディレクトリを削除ではなく移したいのか考えていました。
何を別リポジトリに移すかを考えておかないと、雑多にものが置かれてしまうことを危惧しています。

git管理されているので、単に削除するだけで別リポジトリを作らなくても情報が消えることはありません。
それでも別リポジトリという形で残しておきたいのは、歴史的資料として参照しに行けることに価値があると思っているのと、将来的にコンテンツとして復元しやすくなることの2つが理由にあると思います。
つまりgitの履歴を辿らずとも、アクセスしやすいところに置いておきたいのが理由です。
なお、後者の「将来的にコンテンツとして復元しやすくなること」は、復元時にファイルをコピーしやすくなることよりも、「復元を考えているTODOリスト」として扱えることの方が価値が大きいかなと考えています。



Marshalのようなページに関しては、公開をやめる場合、同様の理由から別リポジトリに移すと良さそうです。もしくは単にリンクを消した上でrurema/doctreeリポジトリに残したままでも良いかもしれません。


refm/old は、「歴史的資料」として別リポジトリに移すと良さそうです。
見た感じ「将来的にコンテンツとして復元」はあまりしなさそうに見えますが、それでも faq と同じリポジトリで良さそうだと感じています。

Ruby/Tk のようなコアから外されたライブラリのドキュメントは  docs.ruby-lang.org/ja に生成済みのファイルが残り続けるので、歴史的資料として残す価値は少ないように思えます。
ruremaとしてこのようなライブラリのドキュメントもサポートしていくという方針になった場合はサルベージしてくる必要がありますが、その場合はgitのログから持ってくればよいし、別リポジトリにしてまで保管する必要は薄いのではと考えています。


mathn も Ruby/Tk の例と同じで、かつ将来的に復元される可能性はより薄いので、別リポジトリに保管する必要は薄いかなと思っています。


まとめると、次の条件のどちらかを満たすものを保管すると良いのではないでしょうか

* rurema/doctreeから削除するとgitのログからしか辿れなくなってしまう、歴史的資料として価値のあるドキュメント
* 将来的にrurema/doctreeに復活させたいけど、メンテができていなくて削除するドキュメント
  * Marshalのことを想定しています。



------




rurema organizationにリポジトリを作る権限がなさそうなので、リポジトリの作成は他の方にお願いしたいです🙏 @znz さんなら権限があるかな。
リポジトリ名は何が良いですかね。 old_documents とか old_doctree とか archived_doctree とかいろいろ浮かびます。

リポジトリを作成頂いた後に、ドキュメントの移行作業は私がやろうと思います

**Comment by scivola** [comment]
Marshal についての

> もしくは単にリンクを消した上でrurema/doctreeリポジトリに残したままでも良いかもしれません。

ですが，それだとページは生成されちゃいませんか？

**Comment by pocke** [comment]
> Marshal についての
> 
> > もしくは単にリンクを消した上でrurema/doctreeリポジトリに残したままでも良いかもしれません。
> 
> ですが，それだとページは生成されちゃいませんか？

おお、なるほど。 ページが生成されるなら消してしまった方が良いですかねえ

**Comment by okkez** [comment]
空のリポジトリ作っときました。
https://github.com/rurema/historical-documents

**Comment by pocke** [comment]
リポジトリの作成ありがとうございます！🙏


https://github.com/rurema/historical-documents/pull/1
faq と refm/old をインポートしてREADMEを追加するPRを作りました。
