### ISSUE TITLE
pack テンプレートの q と Q の説明が間違ってそう

### ISSUE THREAD

**Issue by mrkn** [rurema/doctree#2301]
https://github.com/rurema/doctree/blob/master/refm/api/src/_builtin/pack-template#L314-L343

正しくは、 `q` と `Q` は64ビット整数、`q!` と `Q!` は `long long` のサイズに依存するが、`long long` が無い場合は64ビット整数だと思います。

**Comment by znz** [comment]
(master の URL を指しているので Expand URL to its canonical form した URL をメモしておきます: https://github.com/rurema/doctree/blob/26f8a9504d91a509bb7ed9ff1e83b68c549ba7cf/refm/api/src/_builtin/pack-template#L314-L343 )
