### ISSUE TITLE
Enumerable#include?の例はわかりにくいです

### ISSUE THREAD

**Issue by sidepelican** [rurema/doctree#2303]
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/include=3f.html

`IO.constants` は初学者にはあまり馴染みのない実装だと思います。 `IO.constants` が返す型がEnumerableなのかどうか、そのEnumerableの要素の型が何なのか、分からないです。
素直に整数型などを例にするのが良いのではないでしょうか

**Comment by pocke** [comment]
報告ありがとうございます。
修正してみました。 https://github.com/rurema/doctree/pull/2306
