### ISSUE TITLE
ソースコードをシンタックスハイライトしたらどうでしょうか?

### ISSUE THREAD

**Issue by takiy33** [rurema/doctree#236]
現状のままでも十分見やすいですが、[CodeRay](http://coderay.rubychan.de/)などを使用してシンタックスハイライトすれば更に見やすくなると思います。

**Comment by okkez** [comment]
ソースコードかどうか判断する記法を追加しないと厳しいですね。。。

**Comment by takiy33** [comment]
そうなんですね。了解致しました。 :bow:
