### ISSUE TITLE
BigMath.exp に与える引数の型

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#242]
http://docs.ruby-lang.org/ja/2.3.0/method/BigMath/m/exp.html
では，BigMath.exp の第一引数は

> 計算対象の数値を Fixnum、Bignum、BigDecimal オブジェクトのいずれかで指定します。

となっていますが，Float や Rational を与えることもでき，正しく扱えるようです。

```rb
puts BigMath.exp(-0.69314718, 8) #=> 0.5E0
puts BigMath.exp(1/2r, 9) #=> 0.164872127E1
```

**Comment by sho-h** [comment]
本当ですね。logの方はきちんと書いてるようですので、見落としたのかもしれません。ありがとうございました。
