### ISSUE TITLE
Enumerable#all? の説明文について

### ISSUE THREAD

**Issue by ryy** [rurema/doctree#2422]
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/all=3f.html

> すべての要素が真である場合に true を返します。偽である要素があれば、ただちに false を返します。

偽である要素があれば、ただちに false を返しませんでした。

```
> $ puts [(puts "a"; false;), (puts "b"; true;)].all?

> a
> b
> false
```

**Comment by universato** [comment]
こちらは`all?`メソッドの中で出力されているわけではなく、
配列の初期化の段階で出力されているようです。

```rb
[(puts "a"; false;), (puts "b"; true;)]
# a
# b
```

```rb
x = proc{ puts "a"; false }
[x, x].all?{ |x| x.call }
# a
```

そのため、るびまの記述は正しいと思われます。

**Comment by ryy** [comment]
なるほど！納得いきました！
ありがとうございます👍
