### ISSUE TITLE
Ruby 1.9 以降では require 'rational' が不要では

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#243]
http://docs.ruby-lang.org/ja/1.9.3/method/Rational/i/to_d.html
にある `Rational#to_d` のサンプルコードにおける

```rb
require "rational"
```

は Ruby 1.9 以降では不要ではないでしょうか。

verbose モードだと警告「lib/rational.rb is deprecated」が出ます。

**Comment by sho-h** [comment]
ありがとうございます。削除しました。
