### ISSUE TITLE
Module#refineに記載されているURLがリンク切れを起こしている

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2432]
![image](https://user-images.githubusercontent.com/3800237/104093454-f65d1200-52cd-11eb-8040-ace37717ba9e.png)

原因までは見ていませんが　https://github.com/rurema/doctree/blob/b1282b648e36bb2c2d13e4086afc6d96503d71f1/refm/api/src/_builtin/Module#L1897 の行の **doc** がHTMLへコンバートする過程で消えてしまっているようです。

cf. https://docs.ruby-lang.org/ja/2.4.0/method/Module/i/refine.html

**Comment by krororo** [comment]
#2375 で修正されていそうです。推測ですが、2.4.0はサポート切れのため、ドキュメントの更新がされていないのではないかと思います。

2.5.0以降のドキュメントを確認してみましたが、正しくリンクされているようでした。

**Comment by taki** [comment]
なるほど～。

https://github.com/rurema/doctree/blob/master/CONTRIBUTING.md を参照すると

> それ以前: 対応しない(outdatedな記述は消してもよい)
> 例: 2.1がEOLになったとき、2.0.x で追加されたけど、2.1.x 以降で消えた機能については消してもよい

に当たるので、対応しない感じですね。

**Comment by taki** [comment]
(全然関係ないのですが) krororoさんは長野の方なのですね。私も長野出身なので勝手に親近感が湧きました 😆

**Comment by taki** [comment]
ということで、このIssueはクローズしようかと思います。
