### ISSUE TITLE
Prime::OldCompatibility の記述は消して良さそう？

### ISSUE THREAD

**Issue by taki** [rurema/doctree#2436]
現状のドキュメント整備方針が分かっていなくてすいません。Prime::OldCompatibility は、Ruby 2.3 (該当PR → https://github.com/ruby/ruby/pull/891 ) で消えたので記載自体削除して良いかもと思いました。

cf. https://docs.ruby-lang.org/ja/2.7.0/class/Prime=3a=3aOldCompatibility.html

**Comment by znz** [comment]
https://github.com/rurema/doctree/blob/master/CONTRIBUTING.md#%E5%90%84%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%AE%E5%AF%BE%E5%BF%9C%E6%96%B9%E9%87%9D に書いてあるような方針なので、消してしまって良さそうです。
