### ISSUE TITLE
add `File.absolute_path?`

### ISSUE THREAD

**Issue by no6v** [rurema/doctree#2446]
追加しようと思います(2.7.0 以降)。

**Comment by pocke** [comment]
👀 https://bugs.ruby-lang.org/issues/15868

#2071 で漏れているな、と思ったら、どうやらNEWSに乗っていなかったようですね。ruby/rubyの現在のmasterで`git grep -F 'absolute_path?'`しても見当たらないので、NEWSへの追加し忘れかな。
