### ISSUE TITLE
Encoding::CP65001 の説明

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#246]
Encoding::CP65001
http://docs.ruby-lang.org/ja/2.3.0/method/Encoding/c/CP65001.html
の説明に

>  UTF-8、Unicode や ISO 10646 を ASCII 互換な形で符号化するための方式です。 

とありますが，なにげに読むと「UTF-8 や Unicode や ISO 10646 を ASCII 互換な形で符号化する」のかと誤解します。
「UTF-8」でいったん文を切るとか，もうちょっと語句を足したほうがいいと思います。

**Comment by sho-h** [comment]
本当ですね。 ef61bc9 みたいな感じでしょうか。
