### ISSUE TITLE
Enumerable#chunk の説明

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#247]
Enumerable#chunk
http://docs.ruby-lang.org/ja/2.3.0/method/Enumerable/i/chunk.html
のサンプルの説明に

>  例として、整数列を連続する奇数/偶数に分ける例を見てみます。 「n.even?」が変換するところで区切られているのがわかるでしょう。 

とありますが，

>  「n.even?」が変換するところで

は日本語としておかしいと思います（「変換する」だと，あるものを別のものに変えることなので）。そこで

>  「n.even?」の値が切り替わるところで

としてはどうでしょうか。

また，

> アンダースコアで始まるシンボルはこのメソッドでは予約されています。
> ブロックの返り値としては用いないでください。

とありますが，素直に読めば，「`:_alone` も `:_separator` も使えない？」と誤解します。
この文の意図は「`:_alone` も `:_separator` 以外は使っちゃダメ」ということですよね？

**Comment by sho-h** [comment]
以下な訳ですが、最新の内容に更新しました。

* https://github.com/ruby/ruby/blob/v2_3_0/enum.c#L2853-L2860
* https://github.com/ruby/ruby/blob/v2_3_0/test/ruby/test_enum.rb#L551-L560

**Comment by scivola** [comment]
「それ意外の」→「それ以外の」ですね。

**Comment by sho-h** [comment]
修正しました。
