### ISSUE TITLE
ERB.new の引数の型

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#248]
ERB.new
http://docs.ruby-lang.org/ja/2.3.0/method/ERB/s/new.html
の説明で，第一引数について「eRubyスクリプト」としか書かれていませんが，スクリプトファイルのパスや IO オブジェクトなどではなく，スクリプトそのものの文字列であることをはっきり書いたほうが初心者に親切かと思います（実際には文字列でなくても `to_str` できるものならいいようですが）。
ファイルパスを渡しちゃう勘違いはよくあります。

また，eoutvar についても単に「～をためていく変数」で終わらせず，「～をためていく変数の名前を文字列かシンボルで与えます」くらい書いたほうがよさそうに思います。

**Comment by sho-h** [comment]
ありがとうございます。rdocに引数の名前を合わせつつ概ね上記のようにしました。

> また，eoutvar についても単に「～をためていく変数」で終わらせず，「～をためていく変数の名前を文字列かシンボルで与えます」くらい書いたほうがよさそうに思います。

以下を見る範囲ではシンボルについての記載はないですね。また後者のリンクを見る分にはシンボルで動くのは意図した挙動だとは思えませんでしたので記載しませんでした。

* https://github.com/ruby/ruby/blob/v2_3_0/lib/erb.rb#L747-L750
* https://github.com/ruby/ruby/blob/v2_3_0/lib/erb.rb#L837-L842

**Comment by scivola** [comment]
シンボルは余計でした。
