### ISSUE TITLE
FileUtils.#rmdir の実行例のコメント

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#250]
FileUtils.#rmdir
http://docs.ruby-lang.org/ja/2.3.0/method/FileUtils/m/rmdir.html
の実行例のコメントに

> # does not remove directory really, outputing message.

とあるのですが，「outputing」は「outputting」でしょうか。

そもそも英語である必要は無いので，日本語にしていただけるとありがたいです。

**Comment by sho-h** [comment]
直しました。ruby/rubyの方も同じなら直そうかと思いましたが、そちらはもう直っていました。

自慢することじゃないですが、サンプルコードのコメントは英語のままなものが沢山あると思うのでこういったものはPRいただけると助かります。
