### ISSUE TITLE
Array#rindexの説明について

### ISSUE THREAD

**Issue by Keisuke-goto** [rurema/doctree#2500]
https://docs.ruby-lang.org/ja/latest/method/Array/i/rindex.html
初学者です、勘違いしていたら恐縮なのですが
「ブロックが真を返した最初の要素の位置」とありますが、正しくは「最後の要素の位置」ではないでしょうか？
よろしくお願いいたします。

**Comment by znz** [comment]
> 各要素を引数として順にブロックを実行し、

というのが後ろからなので、最初にブロックが真を返した位置であっていると思うのですが、説明が足りていなくてわかりにくいので、改善できると良さそうです。

```
[10, 11, 12, 13, 14].rindex {|v| p v; v < 13}
14
13
12
# => 2
```

**Comment by Keisuke-goto** [comment]
ご対応ありがとうございます、承知いたしました。
理解が及ばず失礼いたしました
