### ISSUE TITLE
NameError の説明

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#256]
NameError の説明が

>  未定義のローカル変数や定数を使用したときに発生します。 

となっています。
これ自体は完全に正しいですが，NoMethodError のスーパークラスである以上，NoMethodError が出る状況についても書かないと NameError とは何かの説明にはならないような気がします。

**Comment by okkez** [comment]
スーパークラスがサブクラスのことを関知しないのは、一般的なので書かなくてもいいと思います。
