### ISSUE TITLE
"2.5.0 からは require 'irb' せずに直接 binding.irb を呼び出しても使えるようになりました。(実験的)"と言う説明について

### ISSUE THREAD

**Issue by neko314** [rurema/doctree#2582]
https://docs.ruby-lang.org/ja/3.0.0/class/Binding.html#I_IRB の説明は現在このようになっています。
```
irb -> object

REPLのセッションを開始します。

2.5.0 からは require 'irb' せずに直接 binding.irb を呼び出しても使えるようになりました。(実験的)

[SEE_ALSO] irb
```
`2.5.0 からは require 'irb' せずに直接 binding.irb を呼び出しても使えるようになりました。(実験的)`という説明に若干の違和感があったのですが、変更するべきか、変更するとしてどのように変更するのが適切か判断したいと思いissueを立てます。

違和感を抱いたポイントとしては以下のような点です。
* 3.0.0のマニュアルでも`（実験的）`と記載してあると、2.5.0以降ずっと実験的に`require`しなくてもよい状態が続いているように見える
* このように解釈した場合、実験の結果として`require`しないといけなくなるような変更の可能性を感じる

もし変更する場合は`"2.5.0 からは require 'irb' せずに直接 binding.irb を呼び出しても使えるようになりました。(実験的)"` という文全体を削除する、もしくは `"（実験的）"`と言う表記を削除するのどちらかが良いかと思いましたが、いかがでしょうか。

**Comment by znz** [comment]
2.5.0 で experimental という注釈付きの機能として入って、その後何もなかったので正式機能になったという印象なので、「(実験的)」を消してしまえば良さそうです。

experimental というのは他の experimental とついていない機能と比較して、何かあれば戻したり変更したりする可能性が高い、という気持ちでついていることが多くて、特に厳密な基準があるわけではないです。
なので、パターンマッチのような警告がでるような experimental は警告が消えるまで experimental ですが、NEWS に experimental と書いてあるだけのものの場合、次のバージョンでも残っていれば experimental ではなくなってそう、というぐらいで良さそうです。

**Comment by znz** [comment]
ruby-jp slack の方で https://docs.ruby-lang.org/en/master/Coverage.html のように10年以上 experimental のものもあるという話がありました。

**Comment by universato** [comment]
Coverageは英語ドキュメントでもexperimentalと書いてありますけど、
本Issueのirbは、英語ドキュメントにないし、NEWSにexperimentalと書いてあるだけで、
(experimentalになった議論を見つけられなかったので)
るりまの「実験的」の記述は外した方がいいと思います。

「2.5.0 から変更があった」みたいな情報は需要があると思うので、積極的に消す必要はないと思います。

## 参考

[\[意見交換\] Ruby にほしいもの（話題になっていないもので） \- Qiita](https://qiita.com/scivola/questions/3b984e863fdbcb2bd6ec#answer-86355fea64ab0f34ddc0)
> どのバージョンから使えるクラス・メソッドなのかといった情報が欲しいです。

**Comment by neko314** [comment]
> どのバージョンから使えるクラス・メソッドなのかといった情報

確かに私も「いつからこうなったんだろう？」と遡ることがあるので共感します。表記削除の方でPRにしてみました 👍
