### ISSUE TITLE
typo修正について

### ISSUE THREAD

**Issue by Atelier-Mirai** [rurema/doctree#2623]
https://docs.ruby-lang.org/ja/3.0.0/class/String.html

Ruby 学習中のものです。
String クラスの ドキュメント参照いたしました。

``` ruby
例:エンコーディングの変換
s = "ruビー"
s[0..1] = "ル"
p s                  #=> "ルビー"
```

とありますが、「ru」ではなく、「ル」かと思います。
修正頂ければ、幸いです。

``` ruby
例:エンコーディングの変換
s = "ルビー"
s[0..1] = "ル"
p s                  #=> "ルビー"
```

**Comment by universato** [comment]
こんにちは！
`"ruビー"`という文字列の0番目から1番目(つまり`ru`の部分)を`"ル"`で置換する
って内容なので、typo等ではないと思います！

ちなみに、ruをルに置き換えた下の内容だと、
```ruby
s = "ルビー"
s[0..1] = "ル"
p s                  #=> "ルー"
```
最後に表示されるのは、`"ルー"`になってしまいますね。

**Comment by Atelier-Mirai** [comment]
ご回答頂き、ありがとうございます。
文字を置換する例であるにもかかわらず、
typoだと思ってしまい、羞ずかしい限りです。
精進して参りますので、今後ともよろしくお願いいたします。
