### ISSUE TITLE
Module#include が private instance method の方に入っている

### ISSUE THREAD

**Issue by mrkn** [rurema/doctree#269]
2.1 から public instance method になりました。

**Comment by koic** [comment]
こちら https://github.com/rurema/doctree/pull/272 にて対応いたしました。
よろしければ ISSUE の Close をお願いします (コミットメッセージに ISSUE の Close を書いておくべきでした) 。

**Comment by okkez** [comment]
気付いてなかったです。

**Comment by koic** [comment]
ご対応ありがとうございます。
