### ISSUE TITLE
SIGTERMでSignalExceptionが発生する

### ISSUE THREAD

**Issue by okkez** [rurema/doctree#271]
> http://docs.ruby-lang.org/ja/2.1.0/class/SignalException.html
> リファレンスマニュアル的にはSIGTERMではSignalExceptionは発生しないことになっているのですが 
> https://github.com/ruby/ruby/blob/ruby_2_1/signal.c 
> SIGTERMでもSignalExceptionが発生するような実装になっているんです 

るりまが間違ってるんでは？という報告をもらった。

**Comment by znz** [comment]
https://github.com/rurema/doctree/issues/265 と重複?

**Comment by sho-h** [comment]
どうでしょう？ @okkez さん どちらもそんなにたいした情報量がないので、どちらをcloseしてもいいと思います。
少なくとも指摘いただいた内容の修正が必要なのは間違いなさそうですね。上のご指摘はsignal.cの以下のあたりの事ですかねぇ。であればたしかに足りないのはSIGTERMだけっぽいですね。
* https://github.com/ruby/ruby/blob/v2_3_0/signal.c#L1002-L1022

**Comment by sho-h** [comment]
コメントアウトしてmakeするとSignalExceptionが発生しなくなったので合ってそうという事でSIGTERMだけ追加しました。

**Comment by okkez** [comment]
対応ありがとうございます！
