### ISSUE TITLE
Hash#invertについて「異なるキーに対して同じ値が保持されている場合」の挙動が不定ではない?

### ISSUE THREAD

**Issue by takiy33** [rurema/doctree#274]
rdocに「異なるキーに対して同じ値が保持されている場合」の挙動について、不定では無さそうな説明が書いてありました。

Rubyリファレンスマニュアルの場合

> 異なるキーに対して等しい値が登録されている場合の結果は不定であることに 注意してください、そのような場合にこのメソッドを利用することは意図され ていません。

rdocの場合

> If a key with the same value already exists in the hsh, then the last one defined will be used, the earlier value(s) will be discarded.

### 参考

- http://docs.ruby-lang.org/ja/2.3.0/class/Hash.html#I_INVERT
- http://docs.ruby-lang.org/en/2.3.0/Hash.html#method-i-invert

**Comment by znz** [comment]
rdoc の方は https://bugs.ruby-lang.org/issues/10612 で記述が追加されたようで、不定だったとはもともと書いてなかったみたいです。

**Comment by okkez** [comment]
昔は不定だったけど、Hashの順序が不定でなくなったときに同じように `Hash#invert` も不定でなくなったのかしら。

**Comment by takiy33** [comment]
コメントありがとうございます。rdocの記載に合わせるようなPRを出そうと思います。

**Comment by takiy33** [comment]
修正しましたので、クローズします。
