### ISSUE TITLE
Rubyの String#ord と String#getbyte（の中の配列の値）は同じ文字コードを返す

### ISSUE THREAD

**Issue by smapira** [rurema/doctree#2829]
https://docs.ruby-lang.org/ja/latest/method/String/i/getbyte.html

# 提案
「index バイト目」を除く「バイト」を「文字コード」へ置換

# きっかけ

リファレンスマニュアルを読むと、String#getbyteの返り値は「index バイト目のバイトを整数で返します。」、String#ordの返り値は「文字コードを表す整数」と記載があり混乱したため。

# 例
```ruby
'a'.ord
#=> 97

'a'.getbyte 0
#=> 97
```

**Comment by znz** [comment]
実行例が ASCII only の文字列しかないので、ASCII 範囲外の文字の例も入れると混乱しにくくなりそうだと思いました。

```ruby
'あ'.ord
# => 12354
'あ'.getbyte(0)
# => 227
```

**Comment by smapira** [comment]
@znz ありがとうございます、中のコード見てなかったので不適切な内容でした。取り下げます
