### ISSUE TITLE
bundled_gemsの扱い

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#285]
gems/bundled_gemsにある以下の人たちは http://docs.ruby-lang.org/en/trunk/ でも表示されないと思うので、同じように特に記載しないための印を #102 と同様にASSIGN.lowに記載できたらと思っています。

```
power_assert 0.3.0
test-unit 3.2.1
minitest 5.9.0
rake 11.2.2
net-telnet 0.1.1
did_you_mean 1.0.2
xmlrpc 0.1.1
tk 0.1.1
```

記載の内容は以下などですかねえ。

```
-xmlrpc
+xmlrpc                                          bundle gem in 2.4.0
```

特になければそのうち適用してしまいます。

**Comment by okkez** [comment]
rake は日本語でまとまった情報がないので載せておきたいですね。
test-unit みたいに公式サイトがあるやつはそっちへのリンクを載せられるといい気がします。

**Comment by sho-h** [comment]
なるほどです。個人的にはほとんど書けてないものを対象外にできればいいので、既に書いてあるものは載せたままでもいいかもしれません。

**Comment by sho-h** [comment]
c6cf6ca で一部に限定して修正しました。
