### ISSUE TITLE
インタプリタ行の解釈の説明が古い

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#286]
以下に対応する。

https://twitter.com/n0kada/status/742741985186873345

**Comment by okkez** [comment]
> http://docs.ruby-lang.org/ja/2.3.0/doc/spec=2frubycmd.html#shebang … "OSに代わって`#!'に続く文字列をコマンドラインとみなしてそのインタプリタを起動"は1.9.1まで。1.9.2からは-xがあったものとしてshebang行を探す。
