### ISSUE TITLE
るりまサーチの open_search_description.xml ファイルに間違いがあります。

### ISSUE THREAD

**Issue by icm7216** [rurema/doctree#287]
るりまサーチ`http://docs.ruby-lang.org`の web ページ上で Firefox の検索エンジンを登録しました。この後、検索を行うと`http://localhost:9292`を開こうとしますが、開くことができずエラーとなります。

原因を調べたところ`open_search_description.xml`ファイルの URL セクションのホスト名が間違っていることがわかりました。正しくは`http://docs.ruby-lang.org`のところ、`http://localhost:9292`となっています。

この問題のある XML ファイルは次の URL です。
*   http://docs.ruby-lang.org/ja/search/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:1.8.7/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:1.9.3/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:2.0.0/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:2.1.0/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:2.2.0/open_search_description.xml
*   http://docs.ruby-lang.org/ja/search/version:2.3.0/open_search_description.xml

参考として現状の`http://docs.ruby-lang.org/ja/search/open_search_description.xml`の内容です。
``` console
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>るりまサーチ</ShortName>
  <Description>Rubyのリファレンスマニュアルを検索</Description>
  <Image height="16" width="16" type="image/png">http://localhost:9292/ja/search/favicon.png</Image>
  <InputEncoding>UTF-8</InputEncoding>
  <Url type="text/html" method="get" template="http://localhost:9292/ja/search/?query={searchTerms}" />
  <moz:SearchForm>http://localhost:9292/ja/search/</moz:SearchForm>
</OpenSearchDescription>
```

正しくは
``` console
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>るりまサーチ</ShortName>
  <Description>Rubyのリファレンスマニュアルを検索</Description>
  <Image height="16" width="16" type="image/png">http://docs.ruby-lang.org/ja/search/favicon.png</Image>
  <InputEncoding>UTF-8</InputEncoding>
  <Url type="text/html" method="get" template="http://docs.ruby-lang.org/ja/search/?query={searchTerms}" />
  <moz:SearchForm>http://docs.ruby-lang.org/ja/search/</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by okkez** [comment]
https://github.com/clear-code/rurema-search/blob/master/lib/rurema_search/groonga_searcher.rb#L329-331
https://github.com/clear-code/rurema-search/blob/master/lib/rurema_search/groonga_searcher.rb#L370
https://github.com/clear-code/rurema-search/blob/master/config.ru#L95

この辺で設定されているはずの環境変数が、渡って来ていないように見えました。
サーバー側の設定も確認してみたのですが、パっと見た感じ特におかしいところもありませんでした。

たぶんサーバー側の設定だと思うのだけど、よくわかりませんでした。。。

**Comment by icm7216** [comment]
推測ですが、rurema-search の環境を以下でセットアップするところを
```
% sudo sh setup-wheezy.sh docs.ruby-lang.org
```

ローカル環境用にセットアップ（Rack の default port = 9292）を行い。動作確認後そのまま docs.ruby-lang.org にアップロードされたとか?
```
% sudo sh setup-wheezy.sh localhost:9292
```
外していたらゴメンナサイ。

**Comment by okkez** [comment]
docs.ruby-lang.org の設定を直してきちんと動くようにしました。
nginx の設定で proxy_set_header が抜けてたので足したら期待通りの動作になりました。

**Comment by icm7216** [comment]
修正ありがとうございます。
改めて、るりまサーチの検索プラグインを Firefox に登録後、検索バーから正常に検索できるようになったことを確認しました。
