### ISSUE TITLE
Process.warmupの説明がない

### ISSUE THREAD

**Issue by ima1zumi** [rurema/doctree#2873]
Ruby 3.3 から追加された。

[プロと読み解くRuby 3.3 NEWS - STORES Product Blog](https://product.st.inc/entry/2023/12/25/160504#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E5%88%9D%E6%9C%9F%E5%8C%96%E7%B5%82%E4%BA%86%E6%99%82%E3%81%AB%E5%91%BC%E3%81%B6-Processwarmup-%E3%81%8C%E5%B0%8E%E5%85%A5%E3%81%95%E3%82%8C%E3%81%9F)

**Comment by ohai** [comment]
以上2つのPRで追加されたのでissueを閉じました。
