### ISSUE TITLE
NEWSが全てのバージョンで見れる？

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#288]
以下などが見れちゃうようなので修正する。(indexの分岐は正しいはず)

* http://docs.ruby-lang.org/ja/2.1.0/doc/news=2f2_3_0.html

**Comment by okkez** [comment]
HTML生成しちゃってるんですね。。。

**Comment by sho-h** [comment]
うーん、すぐ直せそうとタカをくくってたんですけど、よく考えたらLIBRARIESみたいに指定できないから生成しちゃうんですね...ちょっとすぐ直せそうにないのでIssueをこのまま残して置いときますorz

**Comment by okkez** [comment]
ターゲットバージョンより新しいNEWSでは空っぽのファイルになるようにしておきました。

**Comment by sho-h** [comment]
ありがとうございます！ではいったんcloseして、何か見かけるような事があれば別のIssueにでもしてみようかと思います。
