### ISSUE TITLE
バージョンごとのページが503になっている

### ISSUE THREAD

**Issue by yoshuki** [rurema/doctree#2885]
latestのページは200ですが、バージョンごとのページが503になっています。

- latest: https://docs.ruby-lang.org/ja/latest/class/Hash.html
- バージョンごと: https://docs.ruby-lang.org/ja/3.3/class/Hash.html 

![503](https://github.com/rurema/doctree/assets/9143/f212ce75-533f-4ad8-ac3f-46dd8ac51dad)

**Comment by znz** [comment]
最近バックエンドのEC2のサーバーが無反応になることが何度か発生していて、Mackerel での監視で気付いたら停止して開始しなおして復旧するということをやっています。

根本的な解決策は調査中なので、また発生するかもしれませんが、また発生していたら ruby-jp#rurema などでの報告でも対応可能なので、しばらく待っていても直っていなければ報告していだだけると対応が早くなるかもしれません。

**Comment by yoshuki** [comment]
状況了解しました、返信ありがとうございます。
