### ISSUE TITLE
Dir::Tmpname が無い？

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#291]
私が何か勘違いしているかもしれないのですが、Dir::Tmpname が見当たりません。
何も require しなくても `Dir::Tmpname.make_tmpname("hoge", ".txt")` ってできるので、そういうものはあるんだと思うのですが。

**Comment by sho-h** [comment]
tmpdirライブラリにはDir::Tmpnameがありますがそれですかねぇ。英語の方でもnodocですので、ユーザが使うものではない想定な気がします。るりまでもnodocのものは書かない方針になっているので、わざとではないかと思いました。

「何もrequireしなくても」と言われてる点が気になりますが、僕の環境だと以下のような結果になります。最後のrequireの結果がtrue, trueになったりしません？(確認の仕方がダサい...)。そうなるようなら何か読み込んでるのではないかと思います。

```
$ ruby -ve 'p Dir::Tmpname'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
-e:1:in `<main>': uninitialized constant Dir::Tmpname (NameError)

$ ruby -ve 'require "tmpdir"; p Dir::Tmpname'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Dir::Tmpname

$ ruby -e 'p require "tmpdir"; p require "tmpdir"'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
true
false
```

**Comment by scivola** [comment]
「何もrequireしなくても」は誤りでした。ごめんなさない。（pry 上で実験してました）

nodoc なんですね。じゃあこの件は reject ですね。わかりました。

Qiita に「[衝突しないユニークなファイル名を取得する方法](http://qiita.com/ichiroc@github/items/25e12a9e0d68720784b3)」という記事が出たので、
http://www.rubydoc.info/stdlib/tmpdir/Dir/Tmpname
を見つけて、あれ？リファレンスマニュアルに載ってない？というのが発端でした。
（今よく見たら上記サイトの overview にちゃんと「:nodoc:」って書いてました）

**Comment by sho-h** [comment]
了解です。> pry上で

ではcloseしますね。
