### ISSUE TITLE
h5 が使われている

### ISSUE THREAD

**Issue by znz** [rurema/doctree#294]
http://docs.ruby-lang.org/ja/2.3.0/class/Thread.html の `TimeoutError 対策` などで h5 が使われていて、背景色が赤色で目立つので何かと思って bitclust の方を確認したら、https://github.com/rurema/bitclust/blob/7caeefc3723340204e1cd86eb0abfe6f6ab0a658/theme/default/style.css#L94-L95 などのように css には `/* never use */` とかいてあるので、ドキュメントの方を修正すべきだと思ったのですがどうでしょうか。

ちなみに http://docs.ruby-lang.org/ja/2.3.0/method/Thread/s/handle_interrupt.html のように個別ページの方では h3 になっているようです。

**Comment by sho-h** [comment]
bitclust serverの時と表示が食い違ってるので同じにしとかないと再発しやすいかもしれません。

<img width="894" alt="2016-09-08 12 44 41" src="https://cloud.githubusercontent.com/assets/60238/18336432/2682f7f8-75c2-11e6-8f0b-1fb2ffa135e4.png">

**Comment by znz** [comment]
bitclust server の使い方ってどこかにドキュメントはあるのでしょうか?
