### ISSUE TITLE
default gem と bundled gem について書く

### ISSUE THREAD

**Issue by okkez** [rurema/doctree#303]
http://blog.n-z.jp/blog/2016-09-10-bundled-gem-and-default-gem.html に西山さんがまとめてくれたのでるりまにも書きたい。
それぞれの対応方針については wiki に書きたい。
- default gem: リファレンス書きたい
- bundled gem: gem ごとに判断だけど、書かない方向に倒したい

**Comment by sho-h** [comment]
> * default gem: リファレンス書きたい

賛成です！

> * bundled gem: gem ごとに判断だけど、書かない方向に倒したい

こちらは以下のどちらかを想像したのですが、前者くらいはやっときます？

* gemのドキュメント読んでねページを1枚だけはさむ
* 書かないと判断したものは全く書かない

**Comment by okkez** [comment]
最低限、前者ができるといいですねぇ。

**Comment by sho-h** [comment]
前者の試しにdid_you_meanの概要+gemのドキュメントへのリンクとして、 378f858 をブランチにコミットしてみました(PRはまだ)。[test-unit](https://docs.ruby-lang.org/ja/latest/library/test=2funit.html)は既にそんな風でしたので残った以下を同じ感じにしちゃってよければそうしてしまいます。

* minitest
* net/telnet
* power_assert
* xmlrpc

これにする場合、wikiの内容としてはbundled gemについては対象のgemの確認方法+以下といったところですかねぇ。

* 概要を書く
* プロジェクトページがあれば優先してリンクする
* プロジェクトページがなければgemのドキュメントへのページをリンクする
* 要望が多い場合は内容も記載する

**Comment by okkez** [comment]
ASSIGNファイルには足さなくていいかも。載せるのであれば bundled gem として見出しを付けたいですね。
リンクは以下の全てがいいかなと思います。

* rubygems.org のページ(必ずあるはず)
  * https://rubygems.org/gems/did_you_mean
* github.com のプロジェクトページ(あれば)
  * https://github.com/yuki24/did_you_mean
* rubydoc.info のページ(必ずあるはず)
   * http://www.rubydoc.info/gems/did_you_mean

**Comment by sho-h** [comment]
いくつか修正しました。rakeがそのままにしてありますが、簡素にするのも勿体無いのでわざと今のままにしています。Wikiはどこに書くかが悩ましいですが、FAQですかねぇ。

**Comment by sho-h** [comment]
[ここ](https://github.com/rurema/doctree/wiki/FrequentlyAskedQuestions#default-gem-と-bundled-gemはどう書く)に書いたのでcloseします。
