### ISSUE TITLE
refm/doc/spec/grammar.rd をどうにかする

### ISSUE THREAD

**Issue by okkez** [rurema/doctree#304]
るりまサーチでインデックスされていて、ユーザーから見える状態になってしまっている。
消すか書くかしないと辛い。

**Comment by scivola** [comment]
もう消してしまってよさそうに思いますが、いかがでしょうか。
ファイル自体は old に移すなどして取っておいてもいいかもしれませんけれど。

**Comment by sho-h** [comment]
やるならrdocに合わせたいですねー、と思いましたので #1539 を作成しました。
