### ISSUE TITLE
CC の画像の参照を https にしてほしい

### ISSUE THREAD

**Issue by hsbt** [rurema/doctree#313]
https://github.com/ruby/docs.ruby-lang.org/issues/23 としてリクエストがあった HTTPS 化を行ったところ、 ja のドキュメントに "http://i.creativecommons.org/l/by/3.0/88x31.png" の参照が残っているため HTTPS 通信が invalid となっています。

ドキュメント本体が http でも https で参照することに問題はないと思うので "https://licensebuttons.net/l/by/3.0/88x31.png" に変更していただけないでしょうか。

例: https://docs.ruby-lang.org/ja/2.3.0/doc/index.html

**Comment by okkez** [comment]
BitClust 側の修正が必要なので、やっておきます。

**Comment by okkez** [comment]
https にして bitclust 0.9.3 をリリースしておきました。

**Comment by hsbt** [comment]
無事、 valid HTTPS connection になりました。ありがとうございます。
