### ISSUE TITLE
https://github.com/rurema/doctree の説明の URL

### ISSUE THREAD

**Issue by znz** [rurema/doctree#319]
https://github.com/rurema/doctree のファイル一覧の上の説明の所の URL が http://docs.ruby-lang.org/ja/ のままなので https://docs.ruby-lang.org/ja/ に変更 (https に変更) した方が良いのではないでしょうか。

**Comment by okkez** [comment]
Fixed! Thanks! :boat:

**Comment by znz** [comment]
確認したので閉じます。
