### ISSUE TITLE
Object#singleton_class の Fixnum

### ISSUE THREAD

**Issue by znz** [rurema/doctree#335]
https://github.com/ruby/ruby/commit/dd2ebf4d786ddda1482b6419887c3f6ecbc68567 で `Array#sum` と `Object#singleton_class` の rdoc で `Fixnum` が `Integer` に変更されています。
`Array#sum` はまだ 2.4 からなので、まだるりまに入っていないので、`Object#singleton_class` だけ対応が必要だと思いました。

**Comment by okkez** [comment]
返り値 Fixnum や Bignum になってるやつは全部 Integer にしといてもいいかもですねー。

**Comment by jkr2255** [comment]
[Fixnum自体のページ](https://docs.ruby-lang.org/ja/latest/class/Fixnum.html)も「`Integer`に統合された旨」を書いたページに差し替えるなど、対応が必要ですね。

**Comment by sho-h** [comment]
Array#sumは既に対応が済んでおり、それ以外はunify-integer2ブランチで対応しました。
