### ISSUE TITLE
Integer などの #dup の TypeError

### ISSUE THREAD

**Issue by znz** [rurema/doctree#353]
[Feature #12979 Avoid exception for #dup on Integer (and similar cases)](https://bugs.ruby-lang.org/issues/12979) で nil, true, false, Symbol, Integer (Fixnum) などの dup で TypeError が発生しなくなったようです。
Integer (Bignum) は frozen なので同様に変わるかもしれません。
Rational や Complex は frozen じゃないようなので、変わらないような気がします。

**Comment by znz** [comment]
freeze: false じゃない clone のとき (https://github.com/ruby/ruby/commit/fe3b21bb8c00f20ad45822eb9d95c2e4058e5e5d ) Integer (Bignum) や Float でも (https://github.com/ruby/ruby/commit/7f30d00b53bd5ce680c13f3bcd57e8e29039aaee ) TypeError が発生しなくなったようです。

**Comment by koic** [comment]
以前 #367 として PR を出していたのでした。こちらで解決しているとみなして大丈夫でしょうか？

**Comment by znz** [comment]
対象になりそうな個別のクラスには dup は書かれていなくて、 refm/api/src/_builtin/Object にまとまっていたようなので、解決済みということで良さそうです。

**Comment by koic** [comment]
ありがとうございます！
