### ISSUE TITLE
Ruby 2.4 における Fixnum と Bignum の記述に関して

### ISSUE THREAD

**Issue by osyo-manga** [rurema/doctree#368]
はじめまして。
いつも便利にドキュメントを使わせてもらっています。

さて、Ruby 2.4 において Fixnum と Bignum が Integer へと統合されました。
しかし、ドキュメントの一部において、まだ Fixnum と Bignum の記述が残っているようです（e.g. https://docs.ruby-lang.org/ja/latest/class/Integer.html
このあたりの記述は今後どのような方針で扱われるのでしょうか。修正予定などあるのでしょか。
もし、修正する予定なのであれば、微力ながらお手伝いさせていただきたいと考えています。

**Comment by osyo-manga** [comment]
返信していただきありがとうございます。

> すぐに修正するのは大変なので、少しずつでも修正していきたいと考えていますが、特に予定や期限などは考えていません。

了解致しました。
こちらで修正できる箇所があれば pull request 等投げてしまっても問題ないでしょうか？（確かに一度に修正するのは大変なので少しずつ投げる形になると思いますが。

**Comment by okkez** [comment]
いきなりPRくれた方が捗ります！
大きい修正は見るのが大変なので、小さいPRで全く問題ありません。

**Comment by osyo-manga** [comment]
返信が遅れてしまいもうしわけありません。

> いきなりPRくれた方が捗ります！
> 大きい修正は見るのが大変なので、小さいPRで全く問題ありません。

了解しました。
時間がある時に修正して PR 投げたいと思います。
この issues は閉じてしまいますね。ありがとうございました。
