### ISSUE TITLE
Broken link to minitest/unit

### ISSUE THREAD

**Issue by miyohide** [rurema/doctree#379]
[library test/unit（Ruby 2.4.0）のページ](https://docs.ruby-lang.org/ja/latest/library/test=2funit.html) にて、

> 2.2.0以前のtest/unit は minitest/unit を使って再実装され ていましたが、

という記述がありますが、minitest/unitへのリンクが https://docs.ruby-lang.org/ja/latest/library/minitest=2funit.html となっており、リンク切れとなっています。

Ruby 2.1.0 の minitest/unit のページへのリンク https://docs.ruby-lang.org/ja/2.1.0/library/minitest=2funit.html を貼ればいいかなと思ったのですが、書き方がわからなかったので取り急ぎIssueを記させて頂きました。

**Comment by okkez** [comment]
報告ありがとうございます！

別バージョンのライブラリにリンクを張る必要もなかったのでリンクは削除しました。
かわりに、詳しい歴史がまとまっている記事のリンクを追加しました。
