### ISSUE TITLE
Dir の encoding オプションがない件

### ISSUE THREAD

**Issue by memoma** [rurema/doctree#394]
ずっと気になってたので
Dir.entries( dirname, encoding: enc )
Dir.foreach( dirname, encoding: enc )
Dir.new( string, encoding: enc )
Dir.open( string, encoding: enc )

**Comment by sho-h** [comment]
足してみました。2.1.0からだったようなので、特に分岐は入れていません。NEWSに載ってないようなので見落としてたのかもしれません。ありがとうございました。
