### ISSUE TITLE
Absence Operator

### ISSUE THREAD

**Issue by znz** [rurema/doctree#395]
Ruby 2.4.1 で https://github.com/k-takata/Onigmo/issues/82 の Absent Operator が入りました。
(2.4.0 と 2.4.1 の NEWS の差分参照)

**Comment by znz** [comment]
teeny で分岐はしないというポリシーだったはずなので、`#@since 2.4.0` になるんでしょうか。

**Comment by okkez** [comment]
あー、辛いですね。。。
分岐としては `#@since 2.4.0` にして地の文で「Absent Operator は2.4.1から使えます」って書くのがいいと思います。

**Comment by znz** [comment]
https://github.com/k-takata/Onigmo/issues/87 で absent operator から absence operator に呼び方が変わっています。
