### ISSUE TITLE
対応バージョンの方針

### ISSUE THREAD

**Issue by znz** [rurema/doctree#401]
[Ruby 2.1 公式サポート終了](https://www.ruby-lang.org/ja/news/2017/04/01/support-of-ruby-2-1-has-ended/)しましたが、るりまでの対応バージョンの方針はどこかでまとまっているのでしょうか?

**Comment by okkez** [comment]
https://github.com/rurema/doctree/wiki/ProjectGoal に書いてあるべきですが、書いてませんね。。。
書いときます。

**Comment by okkez** [comment]
と思ったけど、どうしよう。

* 最新安定版(今だと2.4.x): 通常メンテナンス期間なので対応する
* 1つ前の安定版(今だと2.3.x): 通常メンテナンス期間なので対応する
* 2つ前の安定版(今だと2.2.x): セキュリティメンテナンス期間なので対応する
* セキュリティメンテナンス期間が終わってEOLになったもの(今だと2.1.x): 2.1.x特有のものには積極的には対応しないが、既に書いてあるものは消さない。
  * 例: 2.1.x で追加されたけど、2.2.x 以降で消えた機能については残しておく。
* それ以前: 対応しない(outdatedな記述は消してもよい)
  * 例: 2.0.x で追加されたけど、2.1.x 以降で消えた機能については消してもよい。
* あるバージョンがEOLになったらその時点でタグを打つ？

感覚的にはこんな感じが自然だと思いますがどうでしょう？

**Comment by sho-h** [comment]
賛成です！タグもいいですねー。

**Comment by okkez** [comment]
Wikiを書き換えておきました。

**Comment by znz** [comment]
2017年9月25日時点では〜、のように日付固定で良いので、具体例が欲しいと思いました。

**Comment by znz** [comment]
具体例を追加しておきました。
redmine の wiki で EOL などの日付が書いてあるページを探すのにいつも迷っていたので、そこへのリンクも追加しています。
