### ISSUE TITLE
クラスメソッドの定義に矛盾

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#412]
以下では，「クラスメソッド」は「クラスの特異メソッド」であるとしています。
https://docs.ruby-lang.org/ja/latest/doc/spec=2fdef.html#class_method

対して，「用語集」の「クラスメソッド」
https://docs.ruby-lang.org/ja/2.4.0/doc/glossary.html
においては，

> クラスのメソッド。全てのクラスのクラス Classで定義されている 全てのクラスで共有されているメソッドとクラスそれぞれが固有に持っている 特異メソッドとがあるが

としており，Class クラスのインスタンスメソッドも含めていて，矛盾しています。

**Comment by okkez** [comment]
矛盾しているようには見えませんね。。。

> そんなことは大した問題ではない。

って書いてありますし。

**Comment by scivola** [comment]
Class クラスのインスタンスメソッドを含むのか含まないのかはっきりさせていただけるとありがたいのですが，そんなことは大した問題ではない，ということでしたら却下してください。

**Comment by znz** [comment]
曖昧な言い方になってしまいますが、たとえば https://docs.ruby-lang.org/ja/2.4.0/class/Class.html のインスタンスメソッドのうち new はクラスメソッドっぽく感じますが、superclass はあまりクラスメソッドとは呼ばなさそうと感じるので、メソッド個別に人それぞれクラスメソッドと思うかどうかは違うんじゃないのかなと思います。

**Comment by scivola** [comment]
そうすると，Ruby では「クラスメソッド」はハッキリした定義のある言葉ではない，という理解でよいでしょうか？

**Comment by znz** [comment]
JIS ではどうだろうと思って検索してみたところ、http://kikakurui.com/x3/X3017-2013-01.html がみつかり、クラスメソッドと書かれているのは、

> 注記  クラスの特異メソッドは，クラスに対して呼び出すことができるので，他のオブジェクト指向言語でのいわゆるクラスメソッドと類似している。

だけのようだったので、Ruby は言語仕様としてはクラスメソッドは存在しなくて、慣習的に他のオブジェクト指向言語でのクラスメソッド相当のメソッドをクラスメソッドと呼ぶこともある、ということのように思いました。

**Comment by scivola** [comment]
ありがとうございました。未定義語だったのですね。
この手の「一見 Ruby 用語ぽいけど他言語のアナロジーで慣習的に使われてるだけ」の用語って他にもいろいろありそうな気がします。
議論するうえで困るのですが，これはリファレンスマニュアルの問題でなく Ruby の問題なので，ここでこぼしても仕方ありませんね。

**Comment by sho-h** [comment]
closeしておきますが、何か追加であれば開き直してやってくださいませ。m(_ _)m
