### ISSUE TITLE
Net::HTTPExceptionsの内容が一部おかしい?

### ISSUE THREAD

**Issue by murachue** [rurema/doctree#428]
https://github.com/rurema/doctree/blob/master/refm/api/src/net/Net__HTTPExceptions についてです。

# module Net::HTTPExceptionsの一覧

`module Net::HTTPExceptions` の項では

```
  * [[c:Net::HTTPError]]
  * [[c:Net::HTTPRetriableError]]
  * [[c:Net::HTTPServerError]]
  * [[c:Net::HTTPFatalError]]
```

となっていますが、`Net::HTTPServerError`は実際には`Net::HTTPServerException`だと思います。

# class Net::HTTPFatalErrorの説明

`class Net::HTTPFatalError`の項は

```
HTTP ステータスコード 5xx を受け取ったという例外です。

クライアントのリクエストに誤りがあるか、サーバにリクエストを拒否さ
れた(認証が必要、リソースが存在しないなどで)ことを示します。
```

となっています。
2段落目の説明がHTTPステータスコード4xxに紐付く`class Net::HTTPServerException`と同じですが、
`Net::HTTPFatalError`は`Net::HTTPServerError`に紐付くと思うので、
実際は`Net::HTTPServerError`の説明

```
HTTP レスポンス 5xx (Server Error) を表現するクラスです。

サーバがエラーを起こしているなど、サーバ側で処理
を完了することができないことを表しています。
```

のような内容になるべきかなと思います。

**Comment by sho-h** [comment]
ありがとうございます。合ってるように思いましたので 0648c0a で修正しました。
