### ISSUE TITLE
wiki: ClassReferenceManualFormatのリンクの例の整形が崩れてる

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#437]
何か変わったか、以下がうまく整形されなくなってる。

* https://github.com/rurema/doctree/wiki/ClassReferenceManualFormat#ハイパーリンク

**Comment by znz** [comment]
https://githubengineering.com/a-formal-spec-for-github-markdown/ に書いてある sundown (ruby だと redcarpet らしい) から CommonMark への変更の影響っぽいです。(redcarpet gem と commonmarker gem で変換したらそれっぽい感じだったので。)

**Comment by sho-h** [comment]
おぉ、なるほど。今週末くらいにでも他で問題なく整形されてるものも併せて参考にしながら直してみますー。

**Comment by sho-h** [comment]
定義リスト外だと\[\[Hoge]]でエスケープ効いたのですが、定義リスト内だと効かなかったのでまさかの間にコメントタグを挟むという修正をして一旦直しました...(ひどい)

**Comment by okkez** [comment]
cmark のバグかもしれませんねー。
