### ISSUE TITLE
open-uriが見る環境変数の追加

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#484]
以下ではno_proxyがありませんが、

* https://github.com/rurema/doctree/blob/16893428a22b1e0e9e6ef61d5f3c5843cc38172c/refm/api/src/open-uri.rd#L153

たぶん以下のfind_proxyまで降りてno_proxyが設定できる気がするので確認して追加する。
* https://github.com/ruby/ruby/blob/9008d54b12a266356f6aef52388fd4444f0a8d43/lib/uri/generic.rb#L1473-L1487

**Comment by sada** [comment]
こちらのissueの確認をしました。
Ruby 3.2.2の `open-uri` のデフォルトで `no_proxy` 環境変数が有効になっていました。

以下は確認した内容です。

Webrickのプロキシサーバを立ち上げておき、そのopen-uriで `no_proxy` 環境変数の指定によってプロキシ経由でアクセスする／しないを確認しました。

Webrickのプロキシサーバのコード。

```
require "webrick"
require "webrick/httpproxy"

 s = WEBrick::HTTPProxyServer.new(Port: 8080)
 Signal.trap('INT') do
   s.shutdown
 end
 s.start
```

Webrickのプロキシサーバを実行した時のログ。

```
$ ruby proxy.rb
[2023-12-16 15:14:19] INFO  WEBrick 1.8.1
[2023-12-16 15:14:19] INFO  ruby 3.2.2 (2023-03-30) [x86_64-linux]
[2023-12-16 15:14:19] INFO  WEBrick::HTTPProxyServer#start: pid=28219 port=8080
127.0.0.1 - - [16/Dec/2023:15:15:05 JST] "CONNECT 2023.rubyworld-conf.org:443 HTTP/1.1" 200 0
- -> 2023.rubyworld-conf.org:443
```

open-uri のコード。

```
require 'open-uri'

ENV['https_proxy'] = "http://localhost:8080"
ENV['no_proxy'] = "www.ruby-lang.org"

# no_proxy環境変数で設定したホスト名でプロキシを経由しない
URI.open("https://www.ruby-lang.org/en/") {|f|
  f.each_line { |l| puts(l) }
}
# localhost:8080 で立ち上げたプロキシを経由する
URI.open("https://2023.rubyworld-conf.org/ja/") {|f|
  f.each_line { |l| puts(l) }
}
```

`open-uri` の該当位置の説明に `no_proxy` 環境変数を追加します。
