### ISSUE TITLE
サンプル追加の対応リスト作成

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#519]
https://github.com/rurema/doctree/issues/433#issuecomment-324056382 より、サンプルコード未作成のページのうち、対応するメソッドの一覧を作成する。結果はWikiに掲載するかもしれない。

**Comment by okkez** [comment]
対応リスト作るのは、やめません？
リスト作るだけで力尽きそうです。。。
それよりは、ツールでサンプルコードがないエントリをすぐに見つけられるようにしておくのがいいと思いました。
ツールでリスト作って、ツールでリスト更新、ならなんとか続けられるかもしれません。

**Comment by sho-h** [comment]
エントリをすぐに見つけるだけに絞るなら自分的にはstatichtmlでなくbitclustで見る時のメソッド一覧の表の方に「サンプルないよ」マークが表示されてると作業しやすいですねー。

**Comment by hanachin** [comment]
雑に探すスクリプトを書いてみました。
https://github.com/hanachin/rurema-scripts/blob/master/find_rdoc_example.rb

以下のように実行した結果: [result.txt](https://github.com/rurema/doctree/files/1269474/result.txt)

```
% ruby find_rdoc_example.rb 2>/dev/null | sort | uniq | tee result.txt
% cat result.txt | wc -l
348
```

**Comment by hanachin** [comment]
スクリプト雑すぎてうまく検知できてなさそう...少し直してまた結果共有します :bowing_man: 
↑の結果は無視してください〜 :pray:

**Comment by hanachin** [comment]
スクリプト修正して一覧出し直しました。
https://github.com/hanachin/rurema-scripts/blob/fc719b097dbf670cb86247cf57e20e36b03f9e8d/find_rdoc_example.rb

結果: [result.txt](https://github.com/rurema/doctree/files/1269864/result.txt)

```
% cat result.txt | wc -l
147
```

**Comment by sho-h** [comment]
とりあえず、優先する組み込みクラスのrdocありがわかるので、一旦本Issueではそれをゴールにしてcloseしちゃいます。rdocのないものも作りたいみたいな場合は別途立てる事にしようかと。
