### ISSUE TITLE
Wikiのサンプルコードガイドラインの修正

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#523]
[SampleCodeGuideline](https://github.com/rurema/doctree/wiki/SampleCodeGuideline) を整備する。

https://github.com/rurema/doctree/issues/433#issuecomment-317458422 を参照。

**Comment by sho-h** [comment]
https://github.com/rurema/doctree/issues/433#issuecomment-324513266 より。

```
「例:」をつけるかどうかとか、インデントの深さとかはサンプルコードによって違うようなので、ガイドラインで決まっていると悩まなくて良さそうです。
```

https://github.com/rurema/doctree/issues/433#issuecomment-324700722 より。

```
## ガイドラインの修正
>「例:」をつけるかどうかとか、インデントの深さとかはサンプルコードによって違うようなので、
>ガイドラインで決まっていると悩まなくて良さそうです。

例とインデントのルールが決まれば Wiki を変更しておきます。

個人的な意見としては

* 「例」は無しがいいと思います
    * 理由は「例」があると1メソッドに複数サンプルがあったときの場合分けなどルールがめんどうになりそうだから
    * 例の記載がなくても表示フォーマットから例であることは自明であると感じられるから
* インデントはどちらでも
    * 半角2
    * 半角4

追加でもう一つ

* 出力値を併記するときに、サンプルコード内に `p` を書くか書かないかも統一しますか？

  # p がないケース
  "hello世界".chars # => ["h", "e", "l", "l", "o", "世", "界"]

  # p があるケース
  p "foo\n".chomp             # => "foo"
```

**Comment by sho-h** [comment]
僕はまさに複数サンプルがある場合のために「例」みたいなものがある方がうれしいかもです。理由は以下です。

* 複数ある場合に「例」を挟まないと(改行で分けた場合も)1個ににまとめて整形される
    * 例: https://github.com/rurema/doctree/blob/master/refm/api/src/yaml.rd#L5-L70
* サンプルがどこまでで終わりかがわかりやすいほうが初学者向け
* 実行した後でコード読みたい人にもサンプルの範囲はわかりやすい方がいい
    * (コメントで分けると読み飛ばした場合につらそう)

@tbpgr  ルールがめんどうになりそうとの事ですが、明らかにやる事が異なるサンプルを並べて書く場合には分けましょうくらいのルールだと曖昧で嫌ですかね？

確かにサンプルであることは自明かと思いますので、「例」を書くかどうかというよりも分けて表示されてほしいという感じです。例えば文章が間に挟まれるなら「例」なしでも気になりません。

**Comment by tbpgr** [comment]
@sho-h 

>複数ある場合に「例」を挟まないと(改行で分けた場合も)1個ににまとめて整形される

これ、把握できていなかったので他の理由も含めて sho-h さんの提案内容で納得しました。
例ありでいいと思います！ 👍

**Comment by tbpgr** [comment]
一旦仮ぎめして、ガイドラインを修正しようと思いますがいかがでしょう？

* `例:` の記載はサンプルごとにつける
* インデントは半角スペース2で揃える

ひとまずは新規に追加する部分を揃えて、過去分に遡って統一するのは別途ということで。

以下は、保留ということで記載に加えません

* p の有無

目安としてコミッターの方2名以上からリプライ or Emojiリアクションをもらったら修正しようと思っています

**Comment by sho-h** [comment]
僕からは特になくなりました！

pについてはだいたいはirbで試すので自分から書いた事はおそらくほとんどないですが、削除も特にしてないですねー。

**Comment by okkez** [comment]
`p` も値を返すようになっているので `p` については気にしなくていいのではー。

**Comment by znz** [comment]
`p` の有無はとりあえず統一しないにしても、迷った時のために推奨があると良いかもしれません。

**Comment by tbpgr** [comment]
`例:` とインデントについて追記をしました。

![_090517_114415_pm](https://user-images.githubusercontent.com/4787509/30066864-20f466d8-9294-11e7-80ad-6e61493e5f08.jpg)

https://github.com/rurema/doctree/wiki/SampleCodeGuideline

`p` については特別記述していません。

**Comment by tbpgr** [comment]
https://github.com/rurema/doctree/pull/551#issuecomment-327781497

あえてサンプルを書かない物に関する話題が出たのでペタりと。
これも決まりを作って（もしくは特に不要という判断になるか？）ガイドラインに追加ですかね。

**Comment by okkez** [comment]
> 複数のサンプルを続けて記述する場合〜

の例がわかりづらいですね。実際のドキュメントの中から、良い例を見つけてきて書くのがよいのではないでしょうか。
スタイルガイドみたいなの書くときは「悪い例」と「良い例」を書くのがいいです。

**Comment by tbpgr** [comment]
* 例を続けて記載するケースを下部に移動
* sho-h さんに教えていただいたサンプルを例に利用する
* 悪い例と良い例を記載

以上の内容で修正しました

https://github.com/rurema/doctree/wiki/SampleCodeGuideline#%E8%A3%9C%E8%B6%B3%E8%AA%AC%E6%98%8E

**Comment by tbpgr** [comment]
サンプル作成の協力者が増えてきて、作業の競合や完了状況の明確化が必要になっていると思います。
そこで早めに「あえてサンプルを書かないもの」のルールを決めたいなと思っています。

https://github.com/rurema/doctree/pull/551#issuecomment-327781497 で、 znz さんから提案いただいた中で

`#@#noexample ` 

がいいなと思っています。
どうでしょう？

問題なければ、 [SampleCodeGuideline](https://github.com/rurema/doctree/wiki/SampleCodeGuideline) に追加して #433 で協力してくださっている皆さんにシェアしようと思っています。

**Comment by sho-h** [comment]
hashメソッドとかサンプル必要なさそうですもんね。

**Comment by okkez** [comment]
`#@#noexample <サンプルを書かない理由>` でよいのではー。

**Comment by tbpgr** [comment]
追記しました。

[サンプルをあえて書かないケース - SampleCodeGuideline](https://github.com/rurema/doctree/wiki/SampleCodeGuideline#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%92%E3%81%82%E3%81%88%E3%81%A6%E6%9B%B8%E3%81%8B%E3%81%AA%E3%81%84%E3%82%B1%E3%83%BC%E3%82%B9)

この件が問題なさそうならいったんこのIssueは閉じようと思っています。
コメント or リアクションをみて閉じようと思ってます（閉じていただいてもokです）

**Comment by hanachin** [comment]
問題なさそうに見えますー。
Wikiのサンプルをあえて書かないケースの例をStructの方に合わせて修正しました。
https://github.com/rurema/doctree/wiki/SampleCodeGuideline/_compare/c19018fdefdb33b39b60a8986ab7683967d80468...a4d87509515e5aa95b0fab0b9adc9dd6a6403324

**Comment by tbpgr** [comment]
Wikiの修正ありがとうございます 🙏

**Comment by sho-h** [comment]
しばらくなさそうなので一旦closeしちゃいますね。(別途ある場合はそのトピック事に別Issueにする感じを想定
