### ISSUE TITLE
Numeric#abs の説明

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#572]
数値の絶対値を返す abs メソッドは，Numeric，Complex，Fixnum，Bignum，BigDecimal に書かれていますが，Integer，Rational にはありません。

まず，Ruby 2.4 では Fixnum，Bignum はやめて Integer に移すのですよね？

Rational#abs が無いのは意図的とは思えませんので，書く必要があると思います。

Numeric#abs の記述は

>  自身が 0 以上ならば self を、そうでない場合は -self を返します。 

となっています。
「0 以上ならば」は，Complex については当てはまらないので，この記述は適当でないと思います。
また，BigDecimal の場合，0 以上でも abs の返り値は self ではないようです。

```rb
require "bigdecimal"

b = BigDecimal.new("0")
p b.equal?(b.abs) #=> false
```

以上のことから，Numeric#abs の説明は単に

> 自身の絶対値を返します。

にとどめるのが妥当かと思いました。

それから，Complex#abs の返り値が Float となっていますが，以下のように，実部・虚部ともに Integer で，かつ一方が 0 の場合，返り値は Integer になるようです。
（ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15] で確認）

```rb
(0+3i).abs.class #=> Integer
(3+0i).abs.class #=> Integer
```

**Comment by sho-h** [comment]
> まず，Ruby 2.4 では Fixnum，Bignum はやめて Integer に移すのですよね？

ですね。まだなのです。とりえあず、titleからずれてる指摘なので、合わせるかIssueを分解したいと思いました。個人的には1 Issue 1 topicが好きです。終わりが明確になるためです。ご希望がInteger統合ならIssue titleを変えて、そうでないなら、Integer統合を分けてIssueにしたい感じでこのIssueには残りのご希望を書いていただけたらと思います。

> ... Integer，Rational にはありません。
> Rational#abs が無いのは意図的とは思えませんので，書く必要があると思います。

Rational#absについてですが、あるはずだけどるりまにないという事です？以下のようにしてみると2.4から復活してるようですが、るりまを見るとたしかにないですね。

```
$ rbenv each ruby -ve 'r = Rational(1, 2); p r.method(:abs); p r.abs'
...
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin15]
#<Method: Rational(Numeric)#abs>
(1/2)
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
#<Method: Rational#abs>
(1/2)
```

1.9.2以降ではNumeric#absが使われていたので非表示だったのですが、条件を変更しました。

> Complex#abs

本当ですね。直しました。Numericにしていますが、IntegerもFloatも返す可能性があるという意味で他でも使っています。

**Comment by scivola** [comment]
すみません，自分でも「何が言いたいのか解りにくい文章」だと思いました。

Fixnum, Bignum の Integer への統合については，「いずれ統合される予定なのだろうから，issue にしなくていいや」と考えました。
ではなぜ，わざわざ「Integer に移すのですよね？」と書いたかと言いますと，その周辺で「Numeric の下位の具象クラスでおおむね abs の記述があるのに Rational に無いのは抜けなのでは」ということを書きたかったのですが，同じく abs の記述が無い Integer のほうは「いずれ Fixnum，Bignum が統合されたときに abs もやってくるだろうから今この場では Integer のことは無視していいですよね」という確認のためでした。

> Rational#absについてですが、あるはずだけどるりまにないという事です？

はい，るりまに載ってない，という話でした。

**Comment by sho-h** [comment]
了解ですー。では、一旦Integerまわりやってしまいますので少々お待ちください。その後で再度気になる点を本Issueで作業したいと思います！

**Comment by sho-h** [comment]
#578 と #581 の後で 9059174 でNumeric#absの修正をしてみました。Complexまわりのお話しがその通りだと思いましたので、「自身の絶対値を返します。」と提案いただいている通りにしました。

@scivola 特に追加でなければcloseお願いしますー。

**Comment by scivola** [comment]
close の仕方すら知らないヘタレでしたが，画面中を探し回ったら，この下に「Close issue」てボタンが見つかったので押してみます。
あれ，字を入れると「Close and Comment」になるのか，へー。

**Comment by sho-h** [comment]
よくできてますよね。お手数をおかけしました！
