### ISSUE TITLE
Google Analystics を入れた方がいいのでは

### ISSUE THREAD

**Issue by mtsmfm** [rurema/doctree#582]
るりまをどんなユーザが使っているかを知ることは、マニュアルを整備していく上で大事なことだと思ったので issue を立てました。

> Google Analysticsはたぶんつかってないと思います

https://github.com/rurema/doctree/issues/433#issuecomment-324506788

とのことなので、現状使っていないようですが、例えばブラウザの比率からるりまのサポートブラウザを考えることができると思います。

導入にあたってもし何か僕にできそうなことがあればお手伝いさせてください 🙋‍♂️

**Comment by okkez** [comment]
www.ruby-lang.org で使ってそうなのでしばたさんに相談してみます。

**Comment by okkez** [comment]
しばたさんに相談したら早速、権限をもらえました。bitclust側に対応コードを入れ次第、デプロイしたいと思いますが Google Analytics の使い方がいまいちわかってないので、助けてもらえるととってもありがたいです！

**Comment by ikepon** [comment]
よく見られているページや流入元サイトといったGoogle アナリティクスを使ってのデータ分析など、ぜひお手伝いしたいです！

何かできることがあればお手伝いさせてください！

**Comment by hsbt** [comment]
okkez さん以外も GA に追加してみようと思ったんですが google アカウントじゃないとできないようで、RubyKaigi Day 1 の夜ということもあって力尽きてしまいました。

docs.ruby-lang.org というプロパティで管理者権限を @okkez さんに追加しているので、続きはいい感じにお願いしますー。

**Comment by okkez** [comment]
了解です！ありがとうございます！

**Comment by ikepon** [comment]
Google アナリティクスに招待いただきありがとうございます！

ついでといっては何ですが、 [Search Console](https://support.google.com/webmasters#topic=3309469) も設定してみるのはいかがでしょうか？

- ユーザーがどんなワードで検索しているか？
- 検索結果に表示される順位はどのくらいか？

などなど、アナリティクスでは分からない情報が得られ、SEO対策としての情報も得られます！
[Search Console の利点](https://support.google.com/webmasters/answer/4559176?hl=ja)

サイトの所有権を確認する必要があるのですが、Google アナリティクス導入後であればアナリティクスのタグを使って所有確認ができるのでサクッと入れれるかと！

⬇️ 以下のページの【確認方法】部分
https://support.google.com/webmasters/answer/35179

**Comment by tbpgr** [comment]
@ikepon  別件でいくつか 404 になっているケースを見つけています。
GAを活用して404のトラッキングができるようになっていると
実はリンクが切れていたけど気づいていなかった箇所の検出ってできますか？

**Comment by okkez** [comment]
GAの設定&デプロイは完了しましたが、サーチコンソールの設定が終わっていません。
gtag.jsで設定しようとしたのですが、gtag.jsだとサイトの所有権の確認ができないようです。

**Comment by ikepon** [comment]
> gtag.jsで設定しようとしたのですが、gtag.jsだとサイトの所有権の確認ができないようです。

おー！そうなんですね 😓 
であれば別の方法で行う必要がありそうです！

以下のページの「確認方法」内、「HTMLファイルをアップロード」か「HTMLタグ」などが簡単そうです！
[サイトの所有権を確認する](https://support.google.com/webmasters/answer/35179)

ちなみになんですが、 gtag.js にしたのはデフォルトが gtag.js になっていたからでしょうか？

私のウォッチしているGA周りの方は、だいたいの方が BETA 版での使用は避けた方がいいと言っているので analytics.js を使う方が安全かもしれません。
analytics.js であれば Search Console の認証もしてくれると思います。

お手数をおかけしますが、ご検討いただければと！！

[Google アナリティクスの新タグ「gtag.js」はまだ使わないという判断が良いと思う。](https://www.uneidou.com/18062.php)
[Google アナリティクスの新しい計測タグ「gtag.js (BETA)」が登場！](https://kobit.in/archives/10506)

**Comment by okkez** [comment]
> ちなみになんですが、 gtag.js にしたのはデフォルトが gtag.js になっていたからでしょうか？

gtags.js がデフォルトになっていて、推奨されていたので使ってみました。
HTMLファイルをアップロードでやるのが一番簡単で確実っぽいので、ファイルをアップロードする方向でやってみます。

**Comment by okkez** [comment]
HTMLファイルでverifyさせてAnalyticsの権限振った人にはSearchConsoleも見えるようにしたので閉じます。

**Comment by ikepon** [comment]
ありがとうございます！！
