### ISSUE TITLE
Numeric#integer? は整数かどうかを判定するメソッドではない

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#601]
Numeric#integer? の説明が

> self が整数の時、真を返します。そうでない場合に false を返します。 

となっていますが，#600 で追加されたサンプルにも端的に表わされているように，このメソッドは，整数かどうかではなく Integer オブジェクトかどうかを確認するメソッドであるようです。

```rb
0.0.integer? #=> false
(0/1r).integer? #=> false
(0+0i).integer? #=> false

require "bigdecimal"
BigDecimal.new("0").integer? #=> false
```

よって，

> self が Integer オブジェクトの時、真を返します。そうでない場合に false を返します。 

といった表現がいいのではないかと思います。

**Comment by sho-h** [comment]
> 整数かどうかではなく Integer オブジェクトかどうかを確認するメソッドであるようです。
> ...
>> self が Integer オブジェクトの時、真を返します。そうでない場合に false を返します。
>
> といった表現がいいのではないかと思います。

事前情報がない現状だと、(0+0i).integer?や1.to_r.integer?がfalseなのは微妙だと思うので本体の方を直していいのではと思っています。なお、Numeric#integer?は実は常にfalseを返すようですね。

* https://github.com/ruby/ruby/blob/v2_4_0/numeric.c#L762-L766

一方1.integer?はInteger#integer?で常にtrueを返すようにしているため確認していただいたような動きになっているようです。これは`Numeric のサブクラスは、このメソッドを適切に再定義しなければなりません。`の辺りのお話ですね。とりあえずComplex#integer?とRational#integer?はないようですので、以下のように動いてみようかと思いました。

* [ ] るりまで一旦Numeric#integer?の説明を「self が整数の時に true を、そうでない場合に false を返す事が求められるメソッドです。本メソッド自体は常にfalseを返します。」とする
* [ ] 本体でComplex#integer?とRational#integer?が理由があって存在しないか調べてみる
* [ ] 前項で特に理由がなければ本体で両方の#integer?で整数の場合はtrueになるように修正してもらう

**Comment by sho-h** [comment]
なお、2項目で理由がある場合というのは、頂いている`self が Integer オブジェクトの時、真を返します。`で合ってる場合を想定しています。(Integer#integer?のrdocは`Since +int+ is already an Integer, this always returns +true+.`なので合ってるかもなどと思いつつ)

**Comment by scivola** [comment]
ちなみに，ほとんど同じ問題が `Numeric#real?` にもありまして，これも実数（虚部が零）であることを確認するメソッドではなく，Complex オブジェクトではないことを確認するメソッドになっています。

```rb
(1+0i).real? #=> false
```

`integer?` も `real?` も使い道がよく分からない。

もしかしたら，Numeric が備えるべきメソッド一覧を作った人と，実装した人が別人だったりするのでしょうか。

**Comment by sho-h** [comment]
bugs.ruby-lang.org で`complex integer?` や `rational integer?`で検索する分には見当たらないですね...ちょっと調べるのに時間がかかりそうです。

実装した人が同じかはわかりませんが、現状の使われ方としては少なくともIntegerとFloatの範囲くらいなのかもしれませんね。元々の想定通りなので問題ではないのか、単に誰も気づいてないだけなのかは区別が付かない感じですね。

**Comment by sho-h** [comment]
テストを見ればいい事に気付きました。載っているので元々のご指摘の説明にするのが正そうですね。前の僕のコメントの「問題ではない」方という事のようです。

* https://github.com/ruby/ruby/blob/v2_4_2/test/ruby/test_complex.rb#L190-L193

整数とはIntegerの事であり、Complex(1, 0)もComplexなのでIntegerではないという事なんですね。
だとすると今後どうなるにせよ2.4までのドキュメントとしてはどうなるか決まりましたので、#integer?と#real?をそう直して一旦終わりとしたいと思います。

**Comment by sho-h** [comment]
@scivola #609 で修正してみました。特に気になる点がなければマージしてしまいます。

**Comment by scivola** [comment]
はい，これでいいのだと思います。

**Comment by sho-h** [comment]
確認どもでしたー。
