### ISSUE TITLE
rurema.esa.io、Github、gitterの住み分け

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#606]
esa.io を使わせていただけるようになった(大変ありがたい)ので、Github(以下GH)との住み分けを相談できればと思います。(実はgitterもあるそうなので、それも含めて)

* [ ] 住み分けを相談する
* [ ] Wikiにまとめる
    * 役割と参加方法

esa.ioとgitterはそれぞれ以下から確認できます。

* esa.io
    * https://rurema.esa.io
* gitter
    * https://gitter.im/rurema/doctree
    * https://gitter.im/rurema/bitclust

esaは記事を書く形でドキュメントを共有していくサービスというところでしょうか。(docs.esa.io見ただけだったり

gitterはGitHubと連携するチャットツールですかね？Activityが流れるので便利かもしれませんが、esaでもできたりするかもしれません。

重要な情報が分散されない事(決定事項、調査記録等の二重管理は嫌)が大事ですが基本それ以外は自由かなと思っています。

**Comment by sho-h** [comment]
とりあえず自分の意見としては、合意を取っておきたいのは上の「重要な情報が分散されない事」くらいでした。何か相談事が行われたとしてもまぁWiki等に転記する流れがあればいいのではないかといったところです。

おそらくは rurema.esa.io は以下などでが気軽にできればみたいな感じになるのかな？と想像しています。

* ノウハウの共有の場
* Just Idea段階の相談ごと

今までは特に前者がどこにあるかわからなくて参入障壁が高い状態だったと思うのでなんにせよ一回試してみてもいいのではないかと思います。

gitterの方はActivetyを元に必要そうならチャットで相談したりして、重要な事は転記とかそんな感じでしょうか(rurema.esa.io の方でもできるかもしれませんが、まだよくわかってないです)。

**Comment by okkez** [comment]
gitter は雑な相談をする場として使いたいなと思っています。issueにするまでもない質問とか。
場所はこっちかな。 https://gitter.im/rurema-dev/Lobby

リポジトリごとの方は、流量的に今のところ必要ないかなぁと思っています。

**Comment by tbpgr** [comment]
相互参照になってしまいますが、 rurema esa 側でも同様の話題がでたのでURLをはっておきます

https://rurema.esa.io/posts/14

>ノウハウの共有の場
>Just Idea段階の相談ごと

sho-h さんの上記の内容で私も良いと思います。

Gitterの方で話した内容も、何かひとかたまりのトピックとしてやりとりを残したいときは
esaを活用することでストック化するとよさそうです。

**Comment by sho-h** [comment]
> issueにするまでもない質問とか

Issueに起こす前の整理とかにも使えそうですね。

> Gitterの方で話した内容も、何かひとかたまりのトピックとしてやりとりを残したいときは
> esaを活用することでストック化するとよさそうです。

流れさせず記事単位でまとめれるのがいいですね。
簡単な個人のノウハウをメモしておいてもいいですし。
FAQなどにまとめれそうなものはGH Wikiにもっていけばいいですし。

**Comment by tbpgr** [comment]
情報拡散によりまた参加者が増えるかもしれないので、ひとまず rurema esa への導線をWikiに作らねばと思い以下のページを作りました。
（今回追加するまでは #433 と私の個人ブログにしか導線がなかったので ）

https://github.com/rurema/doctree/wiki/Communication-and-knowledge-sharing

Homeのよく使うページへのショートカットの末尾にリンクを追加しました。
記載内容やリンク構成など、修正すべき箇所などあればご指摘ください。

**Comment by znz** [comment]
gitter の URL と簡単な説明を追加しておきました。

**Comment by sho-h** [comment]
wikiありがとうございましたー。
