### ISSUE TITLE
サンプルコードをシンタックスハイライトしたい

### ISSUE THREAD

**Issue by tbpgr** [rurema/doctree#619]
現状るりまではサンプルコードがシンタックスハイライトされていません。

多くの言語の公式リファレンスではサンプルコードがシンタックスハイライトされています。

* [PHP: オブジェクト - Manual](http://php.net/manual/ja/language.types.object.php)
* [The Swift Programming Language (Swift 4): Types](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Types.html#//apple_ref/swift/grammar/array-type)
* [Scala Standard Library 2.12.3 - scala.collection](http://www.scala-lang.org/api/2.12.3/scala/collection/index.html)

特に理由がない場合、シンタックスハイライトを適用することで
ユーザーにとってより見やすいコンテンツになると思いますがいかがでしょうか？

## 関連
https://github.com/google/code-prettify

**Comment by tbpgr** [comment]
まずはシンタックスハイライトが必要かどうかを確認したいと思っています。
必要ということになったら担当してくれる人を募集しようかと思っています。

実際に直すのはたぶん bitclust ですよね。

**Comment by hanachin** [comment]
ruby-docやdocs.ruby-lang.orgやrubydoc.infoなどもシンタックスハイライト効いてますね。
http://ruby-doc.org/core-2.4.0/Integer.html#method-i-odd-3F
https://docs.ruby-lang.org/en/2.4.0/Array.html
http://www.rubydoc.info/

僕は欲しいです ✋

**Comment by okkez** [comment]
今まではサンプルコードを完全に誤りなく検出する方法がなかったのと依存ライブラリを増やしたくなかったので実装していませんでした。

直近では、シンタックスハイライトを目指してというよりも、実行可能なサンプルコードを目指して新機能を追加することを予定しています。
GAの対応が一通り落ちついたら、着手する予定です。

**Comment by tbpgr** [comment]
経緯＋今後に関してありがとうございます 🙏

**Comment by sho-h** [comment]
Redmineは[CodeRay](http://coderay.rubychan.de)使ってハイライトしてるみたいです。

**Comment by okkez** [comment]
依存を増やしたくなかったので、独自に実装しました。
