### ISSUE TITLE
メソッドシグニチャにおけるキーワード引数の書き方

### ISSUE THREAD

**Issue by okkez** [rurema/doctree#668]
今は、ちゃんと決まってなくて書き方が統一されていません。

それを以下のように統一したいです。
基本的にはRubyのコードして読めるメソッドシグニチャにしたいと考えています。
キーワード引数が無い場合はそのようになっています。

```
--- lines(rs = $/, chomp: false) -> String

メソッドの説明は従来通り。

@param rs 引数の説明
@param chomp キーワード引数の説明

@return 返り値の説明。（あれば）

--- some_method(required_keyword:,  optional_keyword: "default_value",  **kw) -> ()

説明

@param required_keyword 必須のキーワード引数の説明〜〜〜。
@param optional_keyword デフォルト値のあるキーワド引数の説明〜〜〜。
@param kw 組み込みライブラリや標準添付ライブラリだとあまりないかもしれない例。

```

引数の名前とキーワード引数の名前を同じように扱う理由は、どちらもそのメソッドの内部ではその名前で参照できるからです。キーワード引数にわざわざ別の名前を付けてしまうと、キーワード引数の名前と別の名前の両方を意識する必要があります。引数の名前とキーワード引数の名前を同じように扱うと、考えることが減るので自然にリファレンスを読むことができるようになると考えます。

また、必須のキーワード引数の場合、別名を付けてしまうとメソッドシグニチャからは必須のキーワード引数であることがわからなくなってしまうので、そのことをを文章で説明する必要があります。

過去にキーワード引数に対応する記法を検討したこともありましたが、上の書き方であれば `@param` とメソッドシグニチャの両方を見ればキーワード引数であることは自明なので、キーワード引数専用の記法は導入したいことにしたいです。

**Comment by znz** [comment]
必須キーワード引数の場合のことや、メソッド内でのローカル変数名に対応するという点で、賛成です。

特に反対意見もないようなので、この方針に決めてしまって、また意見があれば再度検討ということでいいのではないでしょうか。

**Comment by znz** [comment]
[Array#pack](https://bugs.ruby-lang.org/issues/12754) の `buffer:` のように特に初期値はない (内部で確保される文字列オブジェクトになる) 場合はどう書くのが良いでしょうか?

キーワード引数を省略した signature は別の行にあるので、必須キーワード引数のような見た目で以下のように書けば良いでしょうか?

```
--- pack(template)    -> String
#@since 2.4.0
--- pack(template, buffer:)    -> String
#@end

...

@param template 自身のバイナリとしてパックするためのテンプレートを文字列で指定します。
#@since 2.4.0
@param buffer   ...
#@end
```

**Comment by okkez** [comment]
`--- pack(template, buffer: "") -> String` かな？
必須じゃないので、省略可能であることを表現しておきたいです。
`@param buffer` の説明かメソッド自身の説明で`buffer`を省略すると、どうなるか書くとよいのではないでしょうか。

**Comment by znz** [comment]
encoding を考慮すると "" ではなく String.new 相当だと思うので、そのように書いてみました。
https://github.com/rurema/doctree/pull/693

**Comment by sho-h** [comment]
賛成です。(Array#sampleをどうしてあのように指定したんだっけ...

**Comment by sho-h** [comment]
ところで[String.new](https://docs.ruby-lang.org/ja/latest/method/String/s/new.html)も悩ましいですね。
引数string次第なので、正直に書くとたぶん以下みたいになるんですよねぇ。

```
--- new(string = "", encoding: string.encoding, capacity: (string.bytesize > 127) ? string.bytesize : 127) -> String
```

**Comment by sho-h** [comment]
Numeric#stepもbyは1なんですが、toが by > 0 ? inf : -inf的な書き方が必要そうですね。

**Comment by okkez** [comment]
optparse だと典型的な用例ごとにメソッドシグニチャを複数書いているので同じようにすればいいのではー。
あと式を書きたいような場合は、`@param` にちゃんと説明を書くべき。

**Comment by znz** [comment]
https://github.com/rurema/doctree/pull/744 の変更をしていて気づいたのですが、 rdoc だと
https://github.com/ruby/ruby/commit/2c27e52f8ebdf4d382a12b224707d14f2ca589ed#diff-ed091f6c90607ee51d580e3692316fd8R3470 のように

```
 *  call-seq:
 *     ios.each(sep=$/)          {|line| block } -> ios
 *     ios.each(limit)           {|line| block } -> ios
 *     ios.each(sep, limit)      {|line| block } -> ios
 *     ios.each(...)                             -> an_enumerator
 *
 *     ios.each_line(sep=$/)     {|line| block } -> ios
 *     ios.each_line(limit)      {|line| block } -> ios
 *     ios.each_line(sep, limit) {|line| block } -> ios
 *     ios.each_line(...)                        -> an_enumerator
```

という感じで Enumerator を返す例は (ブロック付きの例と重複するので) 引数を省略しているものがあるようですが、るりまではこういう省略はしても良いのでしょうか?

**Comment by okkez** [comment]
これは面倒でも全部書くべきなように思えます。

**Comment by sho-h** [comment]
> 用例ごとにメソッドシグニチャを複数書いて

(string.bytesizeとはちゃんと確認できてないですけど、)以下みたいにしてから `@param` で詳しく説明するというところですか。

```
--- new(string = "", encoding: string.encoding, capacity: 127) -> String
--- new(string = "", encoding: string.encoding, capacity: string.bytesize) -> String

...

@param capacity ◯◯の時は127、××の時はstring.bytesize。
```

**Comment by okkez** [comment]
そんな感じでいいと思います。

**Comment by znz** [comment]
全部書くべき、で了解です。
Enumerable::Enumerator の分岐があると3倍になって大変そうな感じでしたが、もう Enumerable::Enumerator 対応は必要ないので、面倒さは以前よりはましかなと思いました。

**Comment by sho-h** [comment]
#928 までで既存のものは一通り終わりです。
