### ISSUE TITLE
ハッシュ式で{, }を省略できる条件がおかしい？

### ISSUE THREAD

**Issue by JunichiIto** [rurema/doctree#673]
[ハッシュ式](https://docs.ruby-lang.org/ja/2.4.0/doc/spec=2fliteral.html#hash)の説明に、

> ただし、obj[...] 形式のメソッド呼び出しと配列式では、要素全体がハッシュの場合に限り、 {, }を省略することができます。

とありますが、要素全体がハッシュできなくてもメソッドの引数と同様に、末尾の要素がハッシュであれば構文として有効になっているようです。

```
➜  ~ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
➜  ~ irb
irb(main):001:0> [1,2,a:1,b:1]
=> [1, 2, {:a=>1, :b=>1}]
irb(main):002:0> [a:1,b:1]
=> [{:a=>1, :b=>1}]
```

なので、メソッド引数の場合と、obj[...] 形式のメソッド呼び出しと配列式とで説明をわける必要は特にないんじゃないでしょうか？

ちなみに、こちらではRuby 2.1まで上記の動作になることを確認しました。
（Ruby 2.0以前は未確認）

**Comment by pocke** [comment]
Ruby 1.9.3 ~ 2.4 の全部で、末尾の要素がハッシュであれば要素全体がハッシュでなくとも問題ないように見えますね。
https://bacon-cannon.herokuapp.com/parmlinks/333830c4-4f0a-40be-bbdc-1af715a16ddf

**Comment by znz** [comment]
1.8 だとダメだったみたいですが、1.9.3 以降で大丈夫なので、分岐する必要はなさそうです。

```
% ruby -ve 'p [:a=>1,:b=>1]'
ruby 1.8.7 (2013-12-22 patchlevel 375) [x86_64-linux]
[{:a=>1, :b=>1}]
% rbenv each ruby -ve 'p [1,2,:a=>1,:b=>1]'
ruby 1.8.7 (2013-12-22 patchlevel 375) [x86_64-linux]
-e:1: syntax error, unexpected tASSOC, expecting ']'
p [1,2,:a=>1,:b=>1]
           ^
-e:1: warning: useless use of a literal in void context
```

**Comment by JunichiIto** [comment]
なるほど、1.8 => 1.9で変わったようですね。

[こちらのサイト](http://d.hatena.ne.jp/rubikitch/20071224/ruby19)に該当する記述がありました。

```
Arguments to []
---------------
You can use splats and "assocs" (hashes without braces) with [].

ruby 1.9.0:
  class Foo; def [](*a); a end end
  a = (0..3).to_a
  p Foo.new[*a, :op => :+]
  # >> [0, 1, 2, 3, {:op=>:+}]
```

https://docs.ruby-lang.org/en/2.1.0/NEWS-1_9_1.html にもそれらしき記述が。

```
#[] can take splatted arguments, hash style arguments
and a block.
```

**Comment by pocke** [comment]
#2039 で修正されましたのでcloseします
