### ISSUE TITLE
pack template の ?x と "C" の組み合わせの例で例外になる

### ISSUE THREAD

**Issue by znz** [rurema/doctree#694]
https://docs.ruby-lang.org/ja/latest/method/Array/i/pack.html
に、たとえば `[?a, ?b].pack("C @3 C")` という例がありますが、 `TypeError: no implicit conversion of String into Integer` になります。

**Comment by scivola** [comment]
Ruby 1.8 時代は `?a` が整数だったんですよね。
修正するプルリクエストを作りました。

**Comment by scivola** [comment]
この issue は #2164 で解決していますね。

**Comment by hanachin** [comment]
Pull Requestありがとうございました。closeします :pray:
