### ISSUE TITLE
Float::MIN の説明

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#718]
[`Float::MIN`](https://docs.ruby-lang.org/ja/2.4.0/class/Float.html#C_-M-I-N) の説明が

> Float が取り得る最小値

となっているのですが，「Float が取り得る最小の**正の**値」の間違いではないでしょうか。
最小の値は `-Float::MAX` だと思います。

**Comment by sho-h** [comment]
あら、本当ですね。rdocにもそんな風に書いてありました。

**Comment by znz** [comment]
「最小の値は -Float::MAX です。」という注釈もあると良さそうに思いました。

**Comment by scivola** [comment]
一つの issue に書いてよいか分かりませんが，[`Float::MAX`](https://docs.ruby-lang.org/ja/2.4.0/method/Float/c/MAX.html) も

> Float が取り得る最大値

より

> Float が取り得る最大の有限の値

としたほうがよいかもしれません。（`Float::MAX < Float::INFINITY` が真なので）

[`Float::EPSILON`](https://docs.ruby-lang.org/ja/2.4.0/method/Float/c/EPSILON.html) も，

> 1.0 + Float::EPSILON != 1.0 となる最小の値

でなく

> 1.0 + Float::EPSILON != 1.0 となる最小の正の値

が妥当だと思います。

**Comment by sho-h** [comment]
みんなまとめて直してしまいますか。(明日くらいに

**Comment by scivola** [comment]
`INFINITY` のところに，浮動小数点数における負の無限大が `-Float::INFINITY` で得られる，ということも追記するとよさそうです。自明ではないので。
これは，負の無限大が定数として定義されていないことも暗に示唆します。

面白いことに，Rust の浮動小数点数は，Ruby でいうところの

* `-Float::INFINITY`
* `-Float::MAX`
* `Float::MIN`

がそれぞれ，

* [`NEG_INFINITY`](https://doc.rust-lang.org/std/f64/constant.NEG_INFINITY.html)
* [`MIN`](https://doc.rust-lang.org/std/f64/constant.MIN.html)
* [`MIN_POSITIVE`](https://doc.rust-lang.org/std/f64/constant.MIN_POSITIVE.html)

として定義されていました。新しい言語はこういうところが分かりやすくていいですね。

**Comment by sho-h** [comment]
8212e2a で修正してみました。(#728 では他にもいくつかまとめて直しています

**Comment by sho-h** [comment]
追加で修正したので上のコメントも修正。

**Comment by scivola** [comment]
ありがとうございました。
私の判断で閉じちゃっていいのか分かりませんが，閉じちゃってみます。
