### ISSUE TITLE
正規表現の \R の説明に \x{ } が

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#844]
正規表現の `\R` の説明に

```
(?>\x0D\x0A|[\x0A-\x0D\x{85}\x{2028}\x{2029}])
```

とあります。
`\x{85}\x{2028}\x{2029}` は Onigmo のオリジナル（？）の書き方ですが，Ruby では `\u{85}\u{2028}\u{2029}`（もしくは `\u0085\u2028\u2029`）でなければならないと思います。

https://docs.ruby-lang.org/ja/2.4.0/doc/spec=2fregexp.html

**Comment by znz** [comment]
https://github.com/k-takata/Onigmo/blob/669ac9997619954c298da971fcfacccf36909d05/doc/RE.ja には `\u{...}` は書いてなくて `\x{...}` だけしかなくて、 `\R` の説明も Onigmo の説明をそのまま持ってきただけだからっぽい気がします。

**Comment by scivola** [comment]
はい，そのようですね。

Onigmo の RE.ja は Ruby の仕様と若干違うので，持ってくるときに気をつけなければならないのですが，違いを差分の形で記述した文書が見つからないので，どれだけ違いがあるかよく分からないんですよね。

Ruby の正規表現については
https://github.com/ruby/ruby/blob/trunk/doc/re.rdoc
に書いてあるはずなんですが，仕様が網羅されていません。
`\P` も`\R` も載っていないし，trunk なのに非包含オペレーター `(?~ )` もありません。

もう一つ気づきました。
`\R` は CP932 などでも使うことができて，この場合は

```rb
(?>\x0D\x0A|[\x0A-\x0D])
```

になりますが，そのことが書かれていません。

**Comment by znz** [comment]
英語の方は re.rdoc ではなく https://github.com/ruby/ruby/blob/trunk/doc/regexp.rdoc でしょうか。
本家の方のドキュメントなので https://bugs.ruby-lang.org/ の方に issue を書けば対応が早くなるかもしれません。

`\P` は `^` による invert を書いているので省略しているだけかもしれません。
`\R` や `\X` がないのは更新が追いついてないからのような感じがします。
`(?~ )` がないのは experimental だから、という可能性もありそうですが、こちらも単純に更新が追いついてないだけのような気がします。
