### ISSUE TITLE
Dir関連のサンプルにおいて Dir.new よりも Dir.open + Block を利用する

### ISSUE THREAD

**Issue by tbpgr** [rurema/doctree#849]
利用者がコピペした際に思わぬ誤用をするのを防ぐような例になっていることが好ましい。
そのため、安全に Dir が close されるようなコードにしておくために Dir.open + Block を利用する。

下記Issueの流れより。

#846

**Comment by pocke** [comment]
`Dir.new`、及び`Dir.close`のsamplecode以外では`Dir.new`を使っているところはないので、このIssueは完了として良さそうです。修正ありがとうございました🙏
