### ISSUE TITLE
提供されるコマンドが最小限しかない

### ISSUE THREAD

**Issue by sho-h** [rurema/doctree#898]
以下をなんとなく見てたらかなり少ないそうなので追加したい。

* https://docs.ruby-lang.org/ja/latest/doc/spec=2fcommands.html

とりあえずはgemとrakeがあればいいのかもしれない。(他は未確認

**Comment by scivola** [comment]
Ruby 2.5 で `bundle` が追加でしょうか。

**Comment by sho-h** [comment]
そうですねぇ。> bundle

**Comment by znz** [comment]
trunk を make install したら `bundle  bundler  erb  gem  irb  rdoc  ri  ruby` という感じでした。

**Comment by znz** [comment]
bundler は Ruby 2.5 には入らなくなったようです。
https://github.com/ruby/ruby/commit/7825e8363d4b2ccad8e2d3f5eeba9e26f6656911

**Comment by sho-h** [comment]
@znz ありがとうございますー。 #927 でPRにしました。
