### ISSUE TITLE
Ruby 2.1.1版のドキュメントを提供する？

### ISSUE THREAD

**Issue by yhara** [rurema/doctree#93]
### problem

docs.ruby-lang.orgには今のところ2.1.0版しかないようですが、今からRubyを始める人は2.1.1を入れると思うので、「リファレンスがない」と思われるのではないかとちょっと気になりました。

### 対策(案1)

2.1.1や、今後出る2.1.2, 2.1.3などについても項目を用意する。

* pros: わかりやすい。
* cons: いわゆるパッチレベルリリースごとに、docs.ruby-lang.orgの更新とリファレンス生成の追加を行う必要がある。

### 対策(案2)

docs.ruby-lang.orgのリンクを、"2.1.0" ではなく "2.1.x" という記述に変更する。

* pros: メンテが不要なので楽。
* cons: 2.1.0と2.1.1の間で「非互換とも考えられるバグ修正」が入ったときに困る？

### 一言

個人的には案2でよいような気がします(従来もパッチレベル単位のドキュメントは用意してなかったですし)。

**Comment by sho-h** [comment]
closeしてよさそうなので、closeしちゃいますね。
